type State = Record<string, any>;
const rows=(state:State,key:string)=>Array.isArray(state[key])?state[key]:[];
const latest=(items:any[])=>items.map(item=>String(item.updatedAt||item.balanceUpdatedAt||item.createdAt||item.date||"")).filter(Boolean).sort().at(-1)||null;

export function buildAiContextRegistry(state:State){
 const now=new Date().toISOString(),today=now.slice(0,10),domains=[
  {id:"finance",label:"Finance",page:"operations",records:[...rows(state,"bankAccounts"),...rows(state,"financeEntries"),...rows(state,"debts"),...rows(state,"bankTransactions"),...rows(state,"accountBalanceHistory")],authoritative:"SQLite finance records and source-linked balance history",prompts:["Explain my current cash, commitments and debt position","What finance records need attention?","What is my safest next financial action?"]},
  {id:"goals",label:"Goals",page:"executive_planner",records:rows(state,"goals"),authoritative:"Saved goals",prompts:["Which goal needs attention most?","Turn my top goal into approved tasks","Explain my goal progress and risks"]},
  {id:"tasks",label:"Tasks",page:"executive_planner",records:rows(state,"tasks"),authoritative:"Saved personal tasks",prompts:["Prioritize my open tasks","Plan my tasks around my shifts","Which overdue tasks should I reschedule?"]},
  {id:"daily",label:"Daily",page:"planner",records:[...rows(state,"habits"),...rows(state,"focusSessions")],authoritative:"Habit and focus logs",prompts:["Plan today using my real commitments","What should I record today?","Review my recent routines"]},
  {id:"work",label:"Work",page:"work",records:[...rows(state,"workShifts"),...rows(state,"workTasks")],authoritative:"Saved shifts and work tasks",prompts:["What is my next shift and priority?","Plan recovery around my rotation","Help with my work-development goal"]},
  {id:"career",label:"Career",page:"work",records:[...rows(state,"careerProfiles"),...rows(state,"careerDocuments"),...rows(state,"tasks").filter((x:any)=>(x.contextTags||[]).includes("career"))],authoritative:"Verified résumé, honest GitHub evidence audit, saved career preferences and career tasks",prompts:["Assess my career profile and next best move","Turn my experience into a role-targeted plan","Which GitHub project should I finish and prove first?"]},
  {id:"business",label:"Business & Code Learning",page:"work",records:[...rows(state,"goals").filter((x:any)=>x.id==="goal_43v3r"),...rows(state,"tasks").filter((x:any)=>x.goalId==="goal_43v3r"),...rows(state,"projects").filter((x:any)=>x.id==="project_43v3r"),...rows(state,"codeLearningRecords")],authoritative:"43v3r goal, project, tasks, and user-confirmed code understanding history",prompts:["What customer problem does this LifeOS feature solve?","Explain one LifeOS feature in plain language","What code path should I learn next?"]},
  {id:"google",label:"Google Workspace",page:"vault",records:[...(state.googleWorkspace?.calendarEvents||[]),...(state.googleWorkspace?.gmailMessages||[]),...(state.googleWorkspace?.driveFiles||[]),...(state.googleBusinessWorkspace?.tasks||[]),...(state.googleManagedSheets||[]),...(state.googleCrmContacts||[])],authoritative:"User-authorized Google metadata; LifeOS remains authoritative for tasks, finance and CRM links",prompts:["What Google Calendar or Tasks records affect my plan?","Which important emails or CRM follow-ups need attention?","Where are my managed business spreadsheets?"]},
  {id:"memory",label:"Memory",page:"memory",records:rows(state,"aiMemories").filter((x:any)=>x.lifecycleStatus==="active"),authoritative:"Confirmed and controlled memories",prompts:["What does LifeOS remember about me?","Which memories need confirmation?","Check for stale or conflicting memory"]}
 ];
 return {generatedAt:now,policy:{currentRecordsFirst:true,writesRequireApproval:true,secretsExcluded:true,rawDocumentsExcluded:true},domains:domains.map(domain=>({id:domain.id,label:domain.label,page:domain.page,recordCount:domain.records.length,asOf:latest(domain.records),authoritativeSource:domain.authoritative,availableToAi:domain.records.length>0,prompts:domain.prompts,attention:domain.id==="tasks"?domain.records.filter((x:any)=>x.status!=="completed"&&x.dueDate&&x.dueDate<today).length:domain.id==="finance"?rows(state,"bankTransactions").filter((x:any)=>x.status!=="reconciled").length:domain.id==="memory"?rows(state,"aiMemoryCandidates").filter((x:any)=>x.status==="pending").length:0}))};
}

export function workspaceAiContext(registry:ReturnType<typeof buildAiContextRegistry>,workspace:string){
 const aliases:Record<string,string[]>={dashboard:["finance","goals","tasks","work","career","business","google"],executive_planner:["goals","tasks","career","business","google"],planner:["daily","tasks","work","google"],operations:["finance"],work:["work","career","business","tasks","google"],today:["daily","tasks","work","finance","google"],finance:["finance"],debt:["finance"],goals:["goals","tasks","daily"],career:["career","work","tasks","business"],business:["business","work","career","goals","tasks"],system:["memory","google"],system_help:["memory","google"],chat:registry.domains.map(x=>x.id),memory:["memory"],settings:["memory"],vault:["google"]};
 const domains=(aliases[workspace]||[]).map(id=>registry.domains.find(domain=>domain.id===id)).filter((domain):domain is (typeof registry.domains)[number]=>Boolean(domain));
 return {workspace,domains,prompts:[...new Set(domains.flatMap(domain=>domain.prompts))].slice(0,8),generatedAt:registry.generatedAt};
}
