import { createHash, randomUUID } from "node:crypto";
import type { Express } from "express";
import { localDate } from "./workSchedule.js";

export type AutomationRules = { enabled:boolean; categories:Record<string,boolean>; defaultSnoozeMinutes:number; upcomingCommitmentDays:number; staleBalanceDays:number; briefingVisibility:boolean; timingMode:"shift-adaptive"; overrides:Record<string,{wake?:string;sleep?:string}> };
export const DEFAULT_AUTOMATION_RULES:AutomationRules={enabled:true,categories:{tasks:true,finance:true,imports:true,memory:true,habits:true,work:true,google:true},defaultSnoozeMinutes:60,upcomingCommitmentDays:7,staleBalanceDays:30,briefingVisibility:true,timingMode:"shift-adaptive",overrides:{}};
const fingerprint=(...parts:string[])=>createHash("sha256").update(parts.join(":" )).digest("hex").slice(0,32);
const minutes=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return hour*60+minute};
const localTime=(now:Date)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Africa/Johannesburg",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(now);
const plusDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
const dayDifference=(from:string,to:string)=>(new Date(`${to}T12:00:00Z`).getTime()-new Date(`${from}T12:00:00Z`).getTime())/86400000;

export function shiftWindows(daily:any,date:string,rules:AutomationRules){
 const override=rules.overrides?.[date]||{},shift=String(daily.execution?.currentShift?.type||"off").toLowerCase(),afterNight=Boolean(daily.fullDayPlan?.mode==="after-night"||daily.shiftContext?.afterNight);
 const defaults=afterNight?{wake:"14:00",sleep:"08:00",recovery:true}:shift==="day"?{wake:"04:30",sleep:"21:00",recovery:false}:shift==="night"?{wake:"14:00",sleep:"08:00",recovery:true}:{wake:"07:00",sleep:"22:30",recovery:false};
 return {shiftType:shift,expectedWake:override.wake||defaults.wake,protectedSleepStart:override.sleep||defaults.sleep,recovery:defaults.recovery,morningDue:override.wake||defaults.wake,eveningDue:shift==="night"?"16:30":minutes(override.sleep||defaults.sleep)>=60?`${String(Math.floor((minutes(override.sleep||defaults.sleep)-60)/60)).padStart(2,"0")}:${String((minutes(override.sleep||defaults.sleep)-60)%60).padStart(2,"0")}`:"23:00"};
}

type Candidate={fingerprint:string;category:string;priority:"low"|"medium"|"high";title:string;description:string;sourceType:string;sourceId:string|null;targetPage:string;targetSection?:string;effectiveDate:string;expiresAt:string};
export function buildAutomationEvaluation(state:any,daily:any,now=new Date(),rules:AutomationRules={...DEFAULT_AUTOMATION_RULES}){
 const date=daily.asOfDate||localDate("Africa/Johannesburg",now),time=localTime(now),window=shiftWindows(daily,date,rules),candidates:Candidate[]=[];
 const add=(condition:boolean,input:Omit<Candidate,"fingerprint"|"effectiveDate"|"expiresAt"> & {key:string,expiresDays?:number})=>{if(!condition||rules.categories[input.category]===false)return;candidates.push({...input,fingerprint:fingerprint(input.category,input.key,date),effectiveDate:date,expiresAt:`${plusDays(date,input.expiresDays??1)}T00:00:00+02:00`})};
 const openTasks=(state.tasks||[]).filter((item:any)=>item.status!=="completed"),overdue=openTasks.filter((item:any)=>item.dueDate&&item.dueDate<date);
 add(overdue.length>0,{key:"overdue-tasks",category:"tasks",priority:"high",title:`${overdue.length} overdue personal task${overdue.length===1?"":"s"}`,description:"Complete, reschedule, or remove work that is no longer relevant.",sourceType:"task-collection",sourceId:overdue[0]?.id||null,targetPage:"executive_planner",targetSection:"tasks"});
 const overdueWork=(state.workTasks||[]).filter((item:any)=>!["completed","done"].includes(String(item.status).toLowerCase())&&item.dueDate&&item.dueDate<date);
 add(overdueWork.length>0,{key:"overdue-work",category:"work",priority:"high",title:`${overdueWork.length} overdue work task${overdueWork.length===1?"":"s"}`,description:"Review work priorities around the current shift and recovery window.",sourceType:"work-task-collection",sourceId:overdueWork[0]?.id||null,targetPage:"work",targetSection:"tasks"});
 for(const debt of (state.debts||[]).filter((item:any)=>item.status==="Active"&&item.nextDueDate)){const days=dayDifference(date,debt.nextDueDate);add(days<=rules.upcomingCommitmentDays&&days>=0,{key:`debt-${debt.id}-${debt.nextDueDate}`,category:"finance",priority:days<=1?"high":"medium",title:`${debt.name} ${days===0?"is due today":`is due in ${days} days`}`,description:`Expected payment R${Number(debt.minimumPayment||0).toFixed(2)}.`,sourceType:"liability",sourceId:debt.id,targetPage:"operations",targetSection:"debts",expiresDays:Math.max(1,days+1)});}
 const stale=(state.bankAccounts||[]).filter((item:any)=>item.active!==false&&(!item.balanceUpdatedAt||now.getTime()-new Date(item.balanceUpdatedAt).getTime()>rules.staleBalanceDays*86400000));
 add(stale.length>0,{key:"stale-balances",category:"finance",priority:"medium",title:`${stale.length} account balance${stale.length===1?" is":"s are"} stale`,description:"Refresh balances before relying on available-cash guidance.",sourceType:"account-collection",sourceId:stale[0]?.id||null,targetPage:"operations",targetSection:"accounts"});
 const failed=[...(state.bankStatementDocuments||[]),...(state.balanceScreenshotDocuments||[])].filter((item:any)=>item.error||/failed|pending$/i.test(String(item.status||"")));
 add(failed.length>0,{key:"failed-imports",category:"imports",priority:"medium",title:`${failed.length} uploaded document${failed.length===1?" needs":"s need"} attention`,description:"Review extraction diagnostics or retry the saved upload.",sourceType:"uploaded-document",sourceId:failed[0]?.id||null,targetPage:"operations",targetSection:"statements"});
 const pendingTx=(state.bankTransactions||[]).filter((item:any)=>item.status!=="reconciled");
 add(pendingTx.length>0,{key:"transaction-review",category:"finance",priority:"medium",title:`${pendingTx.length} transaction${pendingTx.length===1?"":"s"} await review`,description:"Confirm classifications before relying on final spending analytics.",sourceType:"bank-transaction",sourceId:pendingTx[0]?.id||null,targetPage:"operations",targetSection:"transactions"});
 const pendingMemory=(state.aiMemoryCandidates||[]).filter((item:any)=>item.status==="pending"),conflicts=(state.aiMemories||[]).filter((item:any)=>item.lifecycleStatus==="conflict");
 add(pendingMemory.length+conflicts.length>0,{key:"memory-review",category:"memory",priority:conflicts.length?"high":"medium",title:`${pendingMemory.length+conflicts.length} memory item${pendingMemory.length+conflicts.length===1?"":"s"} need review`,description:"Confirm pending facts and resolve conflicts with current records.",sourceType:"ai-memory",sourceId:conflicts[0]?.id||pendingMemory[0]?.id||null,targetPage:"memory",targetSection:conflicts.length?"conflicts":"review"});
 const googleFailures=Object.values(state.googleSyncServices||{}).filter((item:any)=>item.state==="failed");
 add(googleFailures.length>0,{key:"google-sync",category:"google",priority:"medium",title:`${googleFailures.length} Google service${googleFailures.length===1?" has":"s have"} sync problems`,description:"Open Google Workspace to review the failure and retry time.",sourceType:"google-sync",sourceId:null,targetPage:"vault",targetSection:"google"});
 const important=(state.googleWorkspace?.gmailMessages||[]).filter((item:any)=>item.unread);
 add(important.length>0,{key:"important-email",category:"google",priority:"medium",title:`${important.length} unread important email${important.length===1?"":"s"}`,description:"Review metadata and analyse only messages that need action.",sourceType:"google-email",sourceId:important[0]?.id||null,targetPage:"vault",targetSection:"google"});
 const followUps=(state.googleCrmContacts||[]).filter((item:any)=>item.nextFollowUp&&item.nextFollowUp<=date);
 add(followUps.length>0,{key:"crm-followups",category:"google",priority:"medium",title:`${followUps.length} CRM follow-up${followUps.length===1?" is":"s are"} due`,description:"Review linked contacts and prepare the next approved action.",sourceType:"google-crm-contact",sourceId:followUps[0]?.id||null,targetPage:"vault",targetSection:"google"});
 const missedHabits=(state.habits||[]).filter((item:any)=>!(item.logs||[]).includes(date));
 add(minutes(time)>=18*60&&missedHabits.length>0,{key:"habits-evening",category:"habits",priority:"low",title:`${missedHabits.length} habit${missedHabits.length===1?" remains":"s remain"} today`,description:"Log completed habits or leave them unrecorded; LifeOS will not assume completion.",sourceType:"habit-collection",sourceId:missedHabits[0]?.id||null,targetPage:"planner",targetSection:"today"});
 const morning={kind:"morning",date,title:`Morning briefing · ${window.shiftType} day`,summary:`${overdue.length+overdueWork.length} overdue items; ${daily.day?.summary?.scheduled||0} scheduled; recorded cash R${Number(daily.finance?.cash||0).toFixed(2)}.`,nextAction:daily.recommendedAction,window,sources:["daily-state","tasks","work-shifts","finance","google-metadata"],contextAsOf:daily.generatedAt,provider:"deterministic-local",fallbackReason:null,ready:minutes(time)>=minutes(window.morningDue)};
 const evening={kind:"evening",date,title:"Evening review",summary:`${daily.day?.summary?.completed||0} completed; ${daily.day?.summary?.focusMinutes||0} focus minutes; R${Number(daily.day?.summary?.spending||0).toFixed(2)} spending; ${daily.execution?.habitsCompleted||0}/${daily.execution?.totalHabits||0} habits.`,nextAction:overdue[0]?.title||overdueWork[0]?.title||"Review tomorrow's plan",window,sources:["daily-state","focus-sessions","finance-entries","habit-logs"],contextAsOf:daily.generatedAt,provider:"deterministic-local",fallbackReason:null,ready:minutes(time)>=minutes(window.eveningDue)};
 return {date,time,window,candidates,briefings:[morning,evening]};
}

export function registerDailyAutomationRoutes(app:Express,{state,saveState,audit,getDailyState}:{state:any;saveState:()=>Promise<void>;audit:(action:string,details?:any)=>unknown;getDailyState:(date?:string)=>any}){
 state.automationRules={...DEFAULT_AUTOMATION_RULES,...(state.automationRules||{}),categories:{...DEFAULT_AUTOMATION_RULES.categories,...(state.automationRules?.categories||{})}};state.automationRuns||=[];state.lifeNotifications||=[];state.dailyBriefings||=[];
 let running:Promise<any>|null=null;
 const enhance=async(briefings:any[])=>{const key=state.vault?.nvidiaKey||process.env.NVIDIA_API_KEY;if(!key)return briefings.map(item=>({...item,provider:"deterministic-local",fallbackReason:"NVIDIA is not configured."}));const started=Date.now();try{const response=await fetch("https://integrate.api.nvidia.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(15000),body:JSON.stringify({model:process.env.NVIDIA_MODEL||"nvidia/nemotron-3-super-120b-a12b",messages:[{role:"system",content:"Improve the clarity and encouragement of two LifeOS briefings. Return JSON only: {briefings:[{kind,wording}]}. Do not add facts, numbers, dates, advice, actions, or assumptions. Preserve every supplied fact and only rewrite it concisely."},{role:"user",content:JSON.stringify(briefings.map(item=>({kind:item.kind,title:item.title,summary:item.summary,nextAction:item.nextAction,shiftType:item.window.shiftType})))}],temperature:.1,max_tokens:500,stream:false})});const body:any=await response.json();if(!response.ok)throw new Error(body?.error?.message||`NVIDIA request failed (${response.status}).`);const parsed=JSON.parse(String(body?.choices?.[0]?.message?.content||"").replace(/^```json\s*|\s*```$/g,"")),wording=new Map((parsed.briefings||[]).map((item:any)=>[item.kind,String(item.wording||"").slice(0,700)]));return briefings.map(item=>({...item,aiWording:wording.get(item.kind)||null,provider:"NVIDIA NIM",providerLatencyMs:Date.now()-started,fallbackReason:null}))}catch(error:any){return briefings.map(item=>({...item,provider:"deterministic-local",providerLatencyMs:Date.now()-started,fallbackReason:error.message}))}};
 const evaluate=async(trigger:"startup"|"scheduled"|"manual")=>{if(running)return running;running=(async()=>{const started=Date.now(),now=new Date(),date=localDate("Africa/Johannesburg",now),daily=getDailyState(date),result=buildAutomationEvaluation(state,daily,now,state.automationRules);result.briefings=await enhance(result.briefings.filter(item=>item.ready));const active=new Set(result.candidates.map(item=>item.fingerprint));
   for(const notification of state.lifeNotifications){if(notification.status==="active"&&!active.has(notification.fingerprint)){notification.status="resolved";notification.resolvedAt=now.toISOString();notification.resolution="Condition no longer applies.";}if(notification.expiresAt&&notification.expiresAt<now.toISOString()&&notification.status==="active")notification.status="expired";}
   for(const candidate of result.candidates){const existing=state.lifeNotifications.find((item:any)=>item.fingerprint===candidate.fingerprint);if(existing){if(existing.status==="resolved"||existing.status==="expired")Object.assign(existing,candidate,{status:"active",updatedAt:now.toISOString()});}else state.lifeNotifications.unshift({id:randomUUID(),...candidate,status:"active",isRead:false,createdAt:now.toISOString(),updatedAt:now.toISOString(),delivery:"in-app"});}
   for(const briefing of result.briefings.filter(()=>state.automationRules.briefingVisibility)){const key=`${briefing.date}:${briefing.kind}`,existing=state.dailyBriefings.find((item:any)=>item.key===key);if(existing)Object.assign(existing,briefing,{updatedAt:now.toISOString()});else state.dailyBriefings.unshift({id:randomUUID(),key,...briefing,createdAt:now.toISOString(),updatedAt:now.toISOString()});}
   state.lifeNotifications=state.lifeNotifications.filter((item:any)=>!item.createdAt||Date.now()-new Date(item.createdAt).getTime()<90*86400000).slice(0,500);state.dailyBriefings=state.dailyBriefings.slice(0,180);const run={id:randomUUID(),trigger,startedAt:new Date(started).toISOString(),finishedAt:new Date().toISOString(),durationMs:Date.now()-started,candidates:result.candidates.length,activeNotifications:state.lifeNotifications.filter((item:any)=>item.status==="active").length,status:"success"};state.automationRuns=[run,...state.automationRuns].slice(0,300);audit("daily_automation_evaluated",{runId:run.id,trigger,candidates:run.candidates});await saveState();return {run,result};})().finally(()=>running=null);return running};
 const status=()=>({enabled:state.automationRules.enabled,scheduler:"online",intervalMinutes:5,lastRun:state.automationRuns[0]||null,activeNotifications:state.lifeNotifications.filter((item:any)=>item.status==="active").length,unreadNotifications:state.lifeNotifications.filter((item:any)=>item.status==="active"&&!item.isRead).length,nextEvaluationAt:new Date(Date.now()+5*60000).toISOString(),approvalRequiredForRecordChanges:true,delivery:"in-app"});
 app.get("/api/automation/status",(_req,res)=>res.json(status()));
 app.get("/api/automation/rules",(_req,res)=>res.json(state.automationRules));
 app.put("/api/automation/rules",async(req,res)=>{const body=req.body||{};if(body.defaultSnoozeMinutes!==undefined&&(!Number.isFinite(Number(body.defaultSnoozeMinutes))||Number(body.defaultSnoozeMinutes)<5))return res.status(400).json({code:"INVALID_AUTOMATION_RULES",message:"Default snooze must be at least five minutes.",fieldErrors:{defaultSnoozeMinutes:"Use five minutes or more."}});state.automationRules={...state.automationRules,...body,timingMode:"shift-adaptive",categories:{...state.automationRules.categories,...(body.categories||{})},overrides:{...state.automationRules.overrides,...(body.overrides||{})}};await saveState();res.json(state.automationRules)});
 app.post("/api/automation/evaluate",async(_req,res)=>{try{res.json(await evaluate("manual"))}catch(error:any){res.status(500).json({code:"AUTOMATION_EVALUATION_FAILED",message:error.message,fieldErrors:{},recovery:"No authoritative records were changed. Review automation history and retry."})}});
 app.get("/api/automation/history",(_req,res)=>res.json({runs:state.automationRuns.slice(0,200)}));
 app.get("/api/notifications",(req,res)=>{const includeResolved=req.query.includeResolved==="true",now=new Date().toISOString();res.json({records:state.lifeNotifications.filter((item:any)=>(includeResolved||item.status==="active")&&(!item.snoozedUntil||item.snoozedUntil<=now)),...status()})});
 app.patch("/api/notifications/:id",async(req,res)=>{const item=state.lifeNotifications.find((value:any)=>value.id===req.params.id);if(!item)return res.status(404).json({code:"NOTIFICATION_NOT_FOUND",message:"Notification not found.",fieldErrors:{}});const action=String(req.body.action||"");if(action==="read")item.isRead=true;else if(action==="dismiss"){item.status="dismissed";item.dismissedAt=new Date().toISOString()}else if(action==="resolve"){item.status="resolved";item.resolvedAt=new Date().toISOString();item.resolution="Resolved by user."}else if(action==="snooze"){const duration=Math.max(5,Number(req.body.minutes||state.automationRules.defaultSnoozeMinutes));item.snoozedUntil=new Date(Date.now()+duration*60000).toISOString();item.isRead=true}else return res.status(400).json({code:"INVALID_NOTIFICATION_ACTION",message:"Choose read, dismiss, resolve, or snooze.",fieldErrors:{action:"Unsupported action."}});item.updatedAt=new Date().toISOString();audit("life_notification_updated",{notificationId:item.id,action});await saveState();res.json(item)});
 app.get("/api/personal/briefings/:date",(req,res)=>{const date=/^\d{4}-\d{2}-\d{2}$/.test(req.params.date)?req.params.date:localDate();const records=state.dailyBriefings.filter((item:any)=>item.date===date);res.json({date,records,window:shiftWindows(getDailyState(date),date,state.automationRules),generatedAt:new Date().toISOString()})});
 const timer=setInterval(()=>{if(state.automationRules.enabled)void evaluate("scheduled").catch(()=>undefined)},5*60000);timer.unref();
 return {evaluate,status};
}
