import { isSunday } from "./workSchedule.js";

export type DayPlanPreferences={dayShiftStart:string;dayShiftEnd:string;nightShiftStart:string;nightShiftEnd:string;commuteMinutes:number;offDaySleepStart:string;offDayWake:string;minimumSleepMinutes:number;workoutMinutes:number;relaxMinutes:number};
export const defaultDayPlanPreferences:DayPlanPreferences={dayShiftStart:"06:00",dayShiftEnd:"18:00",nightShiftStart:"18:00",nightShiftEnd:"06:00",commuteMinutes:45,offDaySleepStart:"22:30",offDayWake:"06:30",minimumSleepMinutes:450,workoutMinutes:30,relaxMinutes:90};
const minutes=(time:string)=>{const [hour,minute]=time.split(":").map(Number);return hour*60+minute},time=(value:number)=>`${String(Math.floor(value/60)%24).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
const priority=(value:string)=>({Critical:0,High:1,Medium:2,Low:3}[value]??4);
const dateBefore=(date:string)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()-1);return value.toISOString().slice(0,10)};
type Block={start:string;end:string;category:string;title:string;description?:string;sourceType?:string;sourceId?:string;plannedMinutes?:number;protected?:boolean};
const block=(start:string,end:string,category:string,title:string,description?:string,extra:Partial<Block>={}):Block=>({start,end,category,title,description,plannedMinutes:minutes(end)-minutes(start),...extra});
function pickTasks(tasks:any[],count:number,energy?:string){return [...tasks].filter(task=>task.status!=="completed"&&(!energy||task.energyLevel===energy)).sort((a,b)=>priority(a.priority)-priority(b.priority)||String(a.dueDate||"9999").localeCompare(String(b.dueDate||"9999"))).slice(0,count)}
function assignFocus(blocks:Block[],tasks:any[]){const selected=new Set<string>();return blocks.map(item=>{if(item.category!=="focus")return item;const candidate=tasks.find(task=>!selected.has(task.id)&&(Number(task.estimatedTime||30)<=Number(item.plannedMinutes||0)+30));if(!candidate)return {...item,title:"Study or priority task",description:"Choose the highest-priority open study, health, finance, or business task."};selected.add(candidate.id);return {...item,title:candidate.title,description:`Planned ${Math.min(Number(item.plannedMinutes),Number(candidate.estimatedTime||item.plannedMinutes))} minutes · ${candidate.priority||"Medium"} priority`,sourceType:"task",sourceId:candidate.id}})}
export function validatePlanCoverage(blocks:Block[]){const ordered=[...blocks].sort((a,b)=>a.start.localeCompare(b.start)),errors:string[]=[];let cursor=0;for(const item of ordered){const start=minutes(item.start),end=minutes(item.end);if(start!==cursor)errors.push(`Expected ${time(cursor)}, found ${item.start}`);if(end<=start)errors.push(`Invalid block ${item.start}-${item.end}`);cursor=end;}if(cursor!==1440)errors.push(`Plan ends at ${time(cursor)}, not 24:00`);return {ok:errors.length===0,errors,totalMinutes:ordered.reduce((sum,item)=>sum+Number(item.plannedMinutes||0),0)};}
export function buildEveryMomentPlan(input:{date:string;shifts:any[];tasks:any[];workTasks?:any[];habits?:any[];preferences?:Partial<DayPlanPreferences>}){
 const preferences={...defaultDayPlanPreferences,...input.preferences},shift=input.shifts.find(item=>item.date===input.date)||{date:input.date,type:"off"},previous=input.shifts.find(item=>item.date===dateBefore(input.date)),afterNight=previous?.type==="night"&&shift.type!=="night",sunday=isSunday(input.date);let blocks:Block[]=[];
 if(shift.type==="day")blocks=[block("00:00","04:30","sleep","Protected sleep","Sleep before day shift",{protected:true}),block("04:30","05:00","routine","Wake, hydrate, wash and prayer/reflection"),block("05:00","05:15","meal","Breakfast"),block("05:15","06:00","commute","Travel to work"),block("06:00","18:00","work","Team C day shift","Primary employment shift",{sourceType:"work-shift",sourceId:shift.id,protected:true}),block("18:00","18:45","commute","Travel home and decompress"),block("18:45","19:30","meal","Dinner and family connection"),block("19:30","20:00","health","Mobility, walk or short workout"),block("20:00","20:30","focus","Light study review"),block("20:30","21:00","relax","Screen-light wind-down and prepare tomorrow"),block("21:00","24:00","sleep","Protected sleep","Early sleep for the next shift",{protected:true})];
 else if(shift.type==="night")blocks=[block("00:00","07:00","sleep","Protected overnight sleep",undefined,{protected:true}),block("07:00","07:30","routine","Wake, hydrate, wash and prayer/reflection"),block("07:30","08:00","meal","Breakfast"),block("08:00","08:30","health","Short workout or walk"),block("08:30","09:15","focus","Priority study block"),block("09:15","10:00","routine","Personal admin and finance check"),block("10:00","11:00","relax","Relaxation and family time"),block("11:00","12:00","meal","Lunch and prepare for rest"),block("12:00","16:00","sleep","Protected pre-shift sleep",undefined,{protected:true}),block("16:00","16:30","routine","Wake, wash and prayer/reflection"),block("16:30","17:15","meal","Main pre-shift meal"),block("17:15","18:00","commute","Travel to work"),block("18:00","24:00","work","Team C night shift","Night shift continues into the next date",{sourceType:"work-shift",sourceId:shift.id,protected:true})];
 else if(afterNight)blocks=[block("00:00","06:00","work","Complete Team C night shift","Shift carried from previous date",{sourceType:"work-shift",sourceId:previous.id,protected:true}),block("06:00","06:45","commute","Travel home"),block("06:45","07:30","routine","Light meal, wash and wind-down"),block("07:30","15:00","sleep","Protected recovery sleep",undefined,{protected:true}),block("15:00","15:30","routine","Wake, hydrate and prayer/reflection"),block("15:30","16:00","meal","Recovery meal"),block("16:00","16:30","health","Gentle walk and mobility"),block("16:30","17:00","focus","Low-energy study review"),block("17:00","19:00","relax","Family time and unrestricted relaxation"),block("19:00","19:45","meal","Dinner"),block("19:45","21:00","relax","Quiet leisure"),block("21:00","22:30","routine","Prepare tomorrow and wind down"),block("22:30","24:00","sleep","Protected sleep",undefined,{protected:true})];
 else if(sunday)blocks=[block("00:00","07:30","sleep","Protected sleep",undefined,{protected:true}),block("07:30","08:15","routine","Wake, wash, breakfast and prayer/reflection"),block("08:15","09:00","health","Walk, mobility or gentle workout"),block("09:00","09:30","focus","Quran, Arabic or Islamic study"),block("09:30","12:00","relax","Family, faith and unstructured rest"),block("12:00","13:00","meal","Lunch and prayer/reflection"),block("13:00","15:00","relax","Rest, nap or quiet leisure"),block("15:00","15:45","focus","Weekly review and light planning"),block("15:45","18:30","relax","Family time, recreation and recovery"),block("18:30","19:30","meal","Dinner and prayer/reflection"),block("19:30","21:00","relax","Calm leisure"),block("21:00","22:30","routine","Prepare the week and wind down"),block("22:30","24:00","sleep","Protected sleep",undefined,{protected:true})];
 else blocks=[block("00:00","06:30","sleep","Protected sleep",undefined,{protected:true}),block("06:30","07:00","routine","Wake, hydrate, wash and prayer/reflection"),block("07:00","07:30","meal","Breakfast"),block("07:30","08:00","health","Workout, walk or mobility"),block("08:00","09:00","focus","High-energy priority task"),block("09:00","09:15","relax","Break"),block("09:15","10:00","focus","Study block"),block("10:00","10:30","relax","Tea and reset"),block("10:30","12:00","focus","Deep work for study or 43v3r"),block("12:00","13:00","meal","Lunch and prayer/reflection"),block("13:00","14:00","relax","Rest or nap"),block("14:00","14:45","focus","Finance, admin or learning task"),block("14:45","15:30","routine","Household and personal admin"),block("15:30","17:30","relax","Family time or recreation"),block("17:30","18:15","health","Walk, stretch or active leisure"),block("18:15","19:15","meal","Dinner and prayer/reflection"),block("19:15","20:00","focus","Light Arabic, Islamic or business review"),block("20:00","21:30","relax","Unrestricted relaxation"),block("21:30","22:30","routine","Plan tomorrow and wind down"),block("22:30","24:00","sleep","Protected sleep",undefined,{protected:true})];
 const allTasks=[...input.tasks,...(input.workTasks||[])],ordered=[...pickTasks(allTasks,8,"High"),...pickTasks(allTasks,8,"Medium"),...pickTasks(allTasks,8,"Low"),...pickTasks(allTasks,20)];blocks=assignFocus(blocks,[...new Map(ordered.map(item=>[item.id,item])).values()]);const coverage=validatePlanCoverage(blocks),sleepMinutes=blocks.filter(item=>item.category==="sleep").reduce((sum,item)=>sum+Number(item.plannedMinutes),0),focusMinutes=blocks.filter(item=>item.category==="focus").reduce((sum,item)=>sum+Number(item.plannedMinutes),0),relaxMinutes=blocks.filter(item=>item.category==="relax").reduce((sum,item)=>sum+Number(item.plannedMinutes),0);
 return {date:input.date,dayType:afterNight?"post-night-recovery":sunday?"sunday-rest":shift.type==="day"?"day-shift":shift.type==="night"?"night-shift":"off-day",shiftContext:{type:shift.type||"off",shiftId:shift.id||null,afterNight,sunday,start:shift.start||null,end:shift.end||null,previousShiftType:previous?.type||null,previousShiftId:previous?.id||null},preferences,assumptions:[...(afterNight?["This is an off day immediately after a recorded night shift, so recovery sleep takes priority over productivity."]:[]),...(!shift.start&&["day","night"].includes(shift.type)?[`${shift.type} shift hours use configurable defaults because the imported calendar has no times.`]:[]),"Prayer/reflection blocks are flexible windows, not calculated prayer times."],blocks,summary:{sleepMinutes,focusMinutes,relaxMinutes,healthMinutes:blocks.filter(item=>item.category==="health").reduce((sum,item)=>sum+Number(item.plannedMinutes),0),workMinutes:blocks.filter(item=>item.category==="work").reduce((sum,item)=>sum+Number(item.plannedMinutes),0),scheduledTasks:blocks.filter(item=>item.sourceType==="task").length},coverage};
}
