import { createHash, randomBytes } from "node:crypto";
import type { Express } from "express";

type Dependencies={state:Record<string,any>;saveState:()=>Promise<void>;audit:(action:string,details?:Record<string,any>)=>unknown};
const id=(prefix:string)=>`${prefix}_${randomBytes(10).toString("hex")}`,now=()=>new Date().toISOString(),hash=(value:string)=>createHash("sha256").update(value).digest("hex").slice(0,32);
const envelope=(code:string,message:string,recovery?:string)=>({code,message,fieldErrors:{},...(recovery?{recovery}:{})});
const json=async(response:Response)=>{const body:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||`Google request failed (${response.status}).`);return body};
const token=async(state:any)=>{if(!state.vault?.googleRefreshToken)throw new Error("Google is not connected.");return String((await json(await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:state.vault.googleClientId,client_secret:state.vault.googleClientSecret,refresh_token:state.vault.googleRefreshToken,grant_type:"refresh_token"})}))).access_token||"")};
const get=async(url:string,key:string)=>json(await fetch(url,{headers:{Authorization:`Bearer ${key}`}}));
const write=async(url:string,key:string,method:string,body?:unknown)=>json(await fetch(url,{method,headers:{Authorization:`Bearer ${key}`,...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})}));
const proposal=(type:string,title:string,summary:string,preview:string[],payload:any)=>({id:id("google"),type,title,summary,preview,payload,status:"pending",createdAt:now()});

export function reconcileGoogleTasks(lifeTasks:any[],googleTasks:any[],mappings:any[]){const byLife=new Map(mappings.map(item=>[item.lifeTaskId,item])),byGoogle=new Map(googleTasks.map(item=>[item.id,item])),publish:any[]=[],conflicts:any[]=[],unchanged:any[]=[];for(const task of lifeTasks.filter(item=>item.status!=="completed")){const mapping=byLife.get(task.id);if(!mapping){publish.push(task);continue}const external=byGoogle.get(mapping.googleTaskId);if(!external){conflicts.push({type:"missing-in-google",lifeTask:task,mapping});continue}const changed=String(external.title||"")!==String(task.title||"")||String(external.due||"").slice(0,10)!==String(task.dueDate||"")||external.status==="completed";if(changed)conflicts.push({type:"google-changed",lifeTask:task,googleTask:external,mapping});else unchanged.push(task)}return{publish,conflicts,unchanged,externalOnly:googleTasks.filter(item=>!mappings.some(map=>map.googleTaskId===item.id))}}
export function sheetSnapshot(state:any,kind:string){const month=new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit"}).format(new Date());if(kind==="Monthly Finance Summary")return[["Date","Type","Category","Description","Amount","Source"],...(state.financeEntries||[]).filter((item:any)=>String(item.date).startsWith(month)).map((item:any)=>[item.date,item.type,item.category,item.description,Number(item.amount||0),"LifeOS"] )];if(kind==="Debt Progress")return[["Debt","Balance","Minimum payment","Interest rate","Due date","Status"],...(state.debts||[]).map((item:any)=>[item.name,Number(item.balance||0),Number(item.minimumPayment||0),Number(item.interestRate||0),item.nextDueDate||"",item.status])];if(kind==="Customer Research")return[["Contact","Relationship","Lead stage","Last interaction","Next follow-up","Source"],...(state.googleCrmContacts||[]).map((item:any)=>[item.displayName,item.relationship,item.leadStage,item.lastInteraction||"",item.nextFollowUp||"","LifeOS"] )];if(kind==="Product Roadmap"||kind==="Release Tracker")return[["Task","Status","Priority","Due date","Goal","Source"],...(state.workTasks||[]).map((item:any)=>[item.title,item.status,item.priority,item.dueDate||"",item.goalId||"","LifeOS"] )];return[["Metric","Value","As of","Source"],["Active goals",(state.goals||[]).filter((item:any)=>String(item.status).toLowerCase()==="active").length,now(),"LifeOS"],["Open tasks",(state.tasks||[]).filter((item:any)=>item.status!=="completed").length,now(),"LifeOS"],["Customer records",(state.googleCrmContacts||[]).length,now(),"LifeOS"]]}

export function registerGoogleBusinessRoutes(app:Express,{state,saveState,audit}:Dependencies){
 state.googleTaskMappings||=[];state.googleTaskReconciliations||=[];state.googleManagedSheets||=[];state.googleSheetExportRuns||=[];state.googleCrmContacts||=[];state.googleBusinessWorkspace||={taskLists:[],tasks:[],contacts:[],lastSyncAt:null};
 const pending=(record:any)=>{state.googleActionProposals=[record,...(state.googleActionProposals||[])].slice(0,300);return saveState().then(()=>record)};
 app.get("/api/google/business/status",(_req,res)=>res.json({tasks:{records:state.googleBusinessWorkspace.tasks.length,mappings:state.googleTaskMappings.length,status:state.googleSyncServices?.tasks||null},sheets:{records:state.googleManagedSheets.length,lastExport:state.googleSheetExportRuns[0]||null,status:state.googleSyncServices?.sheets||null},contacts:{records:state.googleBusinessWorkspace.contacts.length,crm:state.googleCrmContacts.length,status:state.googleSyncServices?.contacts||null},lastSyncAt:state.googleBusinessWorkspace.lastSyncAt,authority:"LifeOS"}));
 app.post("/api/google/business/sync",async(_req,res)=>{const access=await token(state).catch(error=>null);if(!access)return res.status(409).json(envelope("GOOGLE_RECONNECT_REQUIRED","Reconnect Google to grant Tasks and Contacts access."));const started=Date.now(),services:any={};try{const lists=await get("https://tasks.googleapis.com/tasks/v1/users/@me/lists?maxResults=100",access),taskLists=lists.items||[],tasks:any[]=[];for(const list of taskLists.slice(0,20)){const response=await get(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(list.id)}/tasks?showCompleted=true&showHidden=true&maxResults=100`,access);tasks.push(...(response.items||[]).map((item:any)=>({...item,taskListId:list.id,taskListTitle:list.title})));}state.googleBusinessWorkspace.taskLists=taskLists;state.googleBusinessWorkspace.tasks=tasks;state.googleSyncServices.tasks={service:"tasks",state:"healthy",lastSuccessAt:now(),latencyMs:Date.now()-started,lastError:null,attempts:0,cursor:tasks.reduce((latest,item)=>String(item.updated||"")>latest?item.updated:latest,"")};services.tasks={records:tasks.length,status:"success"}}catch(error:any){state.googleSyncServices.tasks={service:"tasks",state:"failed",lastError:error.message,retryAt:new Date(Date.now()+15*60000).toISOString()};services.tasks={status:"failed",message:error.message}}try{const people=await get("https://people.googleapis.com/v1/people/me/connections?pageSize=200&personFields=names,emailAddresses,phoneNumbers,organizations,metadata",access);state.googleBusinessWorkspace.contacts=(people.connections||[]).map((person:any)=>({resourceName:person.resourceName,etag:person.etag,displayName:person.names?.[0]?.displayName||"Unnamed contact",email:person.emailAddresses?.[0]?.value||"",phone:person.phoneNumbers?.[0]?.value||"",organization:person.organizations?.[0]?.name||"",title:person.organizations?.[0]?.title||"",sourceLink:"https://contacts.google.com/"}));state.googleSyncServices.contacts={service:"contacts",state:"healthy",lastSuccessAt:now(),latencyMs:Date.now()-started,lastError:null,attempts:0,cursor:people.nextSyncToken||null};services.contacts={records:state.googleBusinessWorkspace.contacts.length,status:"success"}}catch(error:any){state.googleSyncServices.contacts={service:"contacts",state:"failed",lastError:error.message,retryAt:new Date(Date.now()+15*60000).toISOString()};services.contacts={status:"failed",message:error.message}}state.googleSyncServices.sheets={service:"sheets",state:"healthy",lastSuccessAt:now(),latencyMs:Date.now()-started,lastError:null,attempts:0,cursor:state.googleManagedSheets.reduce((latest:any,item:any)=>String(item.updatedAt||"")>latest?item.updatedAt:latest,"")};state.googleBusinessWorkspace.lastSyncAt=now();audit("google_business_synced",services);await saveState();res.json({services,lastSyncAt:state.googleBusinessWorkspace.lastSyncAt})});
 app.get("/api/google/tasks",(_req,res)=>res.json({records:state.googleBusinessWorkspace.tasks,lifeTasks:(state.tasks||[]).filter((item:any)=>item.status!=="completed").map((item:any)=>({id:item.id,title:item.title,dueDate:item.dueDate,status:item.status,published:state.googleTaskMappings.some((map:any)=>map.lifeTaskId===item.id)})),mappings:state.googleTaskMappings,authority:"Google tasks are read-only constraints until an action is approved."}));
 app.post("/api/google/tasks/reconcile-preview",async(_req,res)=>{const diff=reconcileGoogleTasks(state.tasks||[],state.googleBusinessWorkspace.tasks||[],state.googleTaskMappings||[]),record={id:id("taskrecon"),createdAt:now(),...diff};state.googleTaskReconciliations=[record,...state.googleTaskReconciliations].slice(0,100);await saveState();res.json(record)});
 app.post("/api/google/tasks/:lifeTaskId/publish-proposal",async(req,res)=>{const task=(state.tasks||[]).find((item:any)=>item.id===req.params.lifeTaskId);if(!task)return res.status(404).json(envelope("TASK_NOT_FOUND","LifeOS task not found."));res.status(201).json(await pending(proposal("publish-google-task",`Publish task: ${task.title}`,"Creates or updates this task only inside the dedicated LifeOS Google Tasks list.",[task.title,task.dueDate||"No due date"],{lifeTaskId:task.id,snapshot:{title:task.title,dueDate:task.dueDate||null,notes:task.notes||"",goalId:task.goalId||null}})))});
 app.post("/api/google/tasks/:googleTaskId/import-proposal",async(req,res)=>{const task=state.googleBusinessWorkspace.tasks.find((item:any)=>item.id===req.params.googleTaskId);if(!task)return res.status(404).json(envelope("GOOGLE_TASK_NOT_FOUND","Google Task not found."));res.status(201).json(await pending(proposal("import-google-task",`Import suggestion: ${task.title}`,"Creates a new LifeOS task only after approval.",[task.title,String(task.due||"No due date")],{googleTaskId:task.id,taskListId:task.taskListId,snapshot:{title:task.title,dueDate:String(task.due||"").slice(0,10),notes:task.notes||""}})))});
 app.get("/api/google/sheets",(_req,res)=>res.json({records:state.googleManagedSheets,exports:state.googleSheetExportRuns.slice(0,50),authority:"Reporting copies only; SQLite remains authoritative."}));
 app.post("/api/google/sheets/workspace-proposal",async(_req,res)=>{const names=["43v3r Business Metrics","Customer Research","Product Roadmap","Release Tracker","Monthly Finance Summary","Debt Progress"];res.status(201).json(await pending(proposal("create-google-sheets", "Create managed business spreadsheets",`Creates ${names.length} reporting spreadsheets in the LifeOS Drive workspace.`,names,{names})))});
 app.post("/api/google/sheets/:sheetId/export-preview",async(req,res)=>{const sheet=state.googleManagedSheets.find((item:any)=>item.spreadsheetId===req.params.sheetId);if(!sheet)return res.status(404).json(envelope("SHEET_NOT_FOUND","Managed spreadsheet not found."));const rows=sheetSnapshot(state,sheet.name),record=proposal("export-google-sheet",`Export ${sheet.name}`,`Writes ${rows.length-1} current LifeOS rows into the owned data range.`,rows.slice(0,8).map(row=>row.join(" · ")),{spreadsheetId:sheet.spreadsheetId,name:sheet.name,range:"Sheet1!A1:F1000",rows,snapshotHash:hash(JSON.stringify(rows))});res.status(201).json(await pending(record))});
 app.get("/api/google/contacts",(req,res)=>{const query=String(req.query.q||"").toLowerCase(),linked=new Set(state.googleCrmContacts.map((item:any)=>item.resourceName));const records=state.googleBusinessWorkspace.contacts.filter((item:any)=>!query||`${item.displayName} ${item.email} ${item.organization}`.toLowerCase().includes(query)).map((item:any)=>({...item,linked:linked.has(item.resourceName)}));res.json({records,crm:state.googleCrmContacts,privacy:"Only selected contacts become LifeOS CRM records or AI context."})});
 app.post("/api/google/contacts/:resource/import-proposal",async(req,res)=>{const resourceName=decodeURIComponent(req.params.resource),contact=state.googleBusinessWorkspace.contacts.find((item:any)=>item.resourceName===resourceName);if(!contact)return res.status(404).json(envelope("CONTACT_NOT_FOUND","Google contact not found."));const relationship=["family","work","supplier","customer","lead","interview-participant","business-partner"].includes(req.body.relationship)?req.body.relationship:"lead";res.status(201).json(await pending(proposal("import-google-contact",`Link ${contact.displayName} to LifeOS CRM`,"Stores selected contact metadata and follow-up fields after approval.",[contact.displayName,contact.organization||"No organization",relationship],{resourceName,relationship,leadStage:req.body.leadStage||"New",nextFollowUp:req.body.nextFollowUp||null,snapshot:contact})))});
 app.post("/api/google/contacts/create-proposal",async(req,res)=>{const displayName=String(req.body.displayName||"").trim();if(!displayName)return res.status(400).json(envelope("INVALID_CONTACT","Contact name is required."));res.status(201).json(await pending(proposal("create-google-contact",`Create Google contact: ${displayName}`,"Creates one contact only after approval.",[displayName,String(req.body.email||""),String(req.body.organization||"")],{displayName,email:String(req.body.email||""),phone:String(req.body.phone||""),organization:String(req.body.organization||""),relationship:req.body.relationship||"lead"})))});
 app.post("/api/google/calendar/freebusy",async(req,res)=>{try{const access=await token(state),timeMin=new Date(req.body.timeMin||Date.now()).toISOString(),timeMax=new Date(req.body.timeMax||Date.now()+7*86400000).toISOString(),calendarIds=Array.isArray(req.body.calendarIds)&&req.body.calendarIds.length?req.body.calendarIds.slice(0,20):["primary"],result=await write("https://www.googleapis.com/calendar/v3/freeBusy",access,"POST",{timeMin,timeMax,timeZone:"Africa/Johannesburg",items:calendarIds.map((calendarId:string)=>({id:calendarId}))});res.json({timeMin,timeMax,calendars:result.calendars||{},readOnly:true})}catch(error:any){res.status(502).json(envelope("GOOGLE_FREEBUSY_FAILED",error.message,"Reconnect Google or retry after Calendar service recovery."))}});
 app.get("/api/google/drive/:fileId/revisions",async(req,res)=>{try{const file=(state.googleWorkspace?.driveFiles||[]).find((item:any)=>item.id===req.params.fileId),managed=String(file?.description||"").toLowerCase().includes("lifeos")||(state.googleActionProposals||[]).some((item:any)=>(item.result||[]).some((result:any)=>result.id===req.params.fileId));if(!managed)return res.status(403).json(envelope("DRIVE_FILE_NOT_MANAGED","Revision history is available only for managed LifeOS files."));const access=await token(state),result=await get(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(req.params.fileId)}/revisions?pageSize=100&fields=revisions(id%2CmodifiedTime%2CkeepForever%2Cpublished%2Csize%2CexportLinks)`,access);res.json({fileId:req.params.fileId,revisions:result.revisions||[]})}catch(error:any){res.status(502).json(envelope("DRIVE_REVISIONS_FAILED",error.message))}});
}
