import { createHash, randomBytes } from "node:crypto";
import type { Express } from "express";

type State = Record<string, any>;
type Dependencies = { state: State; saveState: () => Promise<void>; audit: (action: string, details?: Record<string, any>) => unknown; getDayPlan: (date: string) => any };
type Service = "calendar" | "gmail" | "drive" | "tasks" | "sheets" | "contacts";

const SERVICES: Service[] = ["calendar", "gmail", "drive", "tasks", "sheets", "contacts"];
const nowIso = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${randomBytes(10).toString("hex")}`;
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const errorEnvelope = (code: string, message: string, recovery?: string) => ({ code, message, fieldErrors: {}, ...(recovery ? { recovery } : {}) });
const googleJson = async (response: Response) => { const body: any = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || `Google request failed (${response.status}).`); return body; };
const token = async (state: State) => {
  if (!state.vault?.googleRefreshToken) throw new Error("Google is not connected.");
  return String((await googleJson(await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: state.vault.googleClientId, client_secret: state.vault.googleClientSecret, refresh_token: state.vault.googleRefreshToken, grant_type: "refresh_token" }) }))).access_token || "");
};
const get = async (url: string, accessToken: string) => googleJson(await fetch(url, { headers: { Authorization: `Bearer ${accessToken}` } }));
const write = async (url: string, accessToken: string, method: string, body?: unknown) => googleJson(await fetch(url, { method, headers: { Authorization: `Bearer ${accessToken}`, ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }));
const header = (message: any, name: string) => String(message?.payload?.headers?.find((item: any) => String(item.name).toLowerCase() === name.toLowerCase())?.value || "");
const decode = (value: string) => Buffer.from(value.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf8");
const strip = (value: string) => value.replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();
const bodyText = (payload: any): string => {
  if (payload?.mimeType === "text/plain" && payload.body?.data) return decode(payload.body.data);
  const plain = (payload?.parts || []).find((part: any) => part.mimeType === "text/plain" && part.body?.data);
  if (plain) return decode(plain.body.data);
  const html = (payload?.parts || []).find((part: any) => part.mimeType === "text/html" && part.body?.data);
  return html ? strip(decode(html.body.data)) : "";
};

export function nextRetry(attempt: number, at = Date.now()) { return new Date(at + Math.min(60, 2 ** Math.max(0, attempt)) * 60_000).toISOString(); }
export function calendarFingerprint(sourceKey: string) { return hash(`lifeos-calendar:${sourceKey}`).slice(0, 32); }
export function emailSelectionReason(message: any, rules: any[] = []) {
  const labels = message.labelIds || [], from = String(message.from || "").toLowerCase(), subject = String(message.subject || "").toLowerCase();
  const rule = rules.find(item => item.active !== false && ((item.sender && from.includes(String(item.sender).toLowerCase())) || (item.subject && subject.includes(String(item.subject).toLowerCase()))));
  return rule ? `approved rule: ${rule.name || rule.sender || rule.subject}` : labels.includes("IMPORTANT") ? "Gmail important" : labels.includes("STARRED") ? "starred" : labels.includes("UNREAD") ? "unread" : null;
}
export function reconcileCalendar(desired: any[], existing: any[]) {
  const owned = existing.filter(item => item.owned), external = existing.filter(item => !item.owned), bySource = new Map(owned.map(item => [item.sourceKey, item]));
  const creates: any[] = [], updates: any[] = [], unchanged: any[] = [];
  for (const item of desired) {
    const current = bySource.get(item.sourceKey); bySource.delete(item.sourceKey);
    if (!current) creates.push(item);
    else if (current.title !== item.title || current.start !== item.start || current.end !== item.end) updates.push({ before: current, after: item });
    else unchanged.push(item);
  }
  const overlaps = (a: any, b: any) => String(a.start) < String(b.end) && String(a.end) > String(b.start);
  const conflicts = desired.flatMap(item => external.filter(event => overlaps(item, event)).map(event => ({ desired: item, external: event, reason: "Personal Google event overlaps this LifeOS block." })));
  return { creates, updates, removals: [...bySource.values()], unchanged, conflicts };
}
export function searchDriveIndex(records: any[], query: string, limit = 8) {
  const terms = query.toLowerCase().split(/\W+/).filter(term => term.length > 2);
  return records.map(record => { const text = `${record.name || ""} ${record.extractedText || ""}`.toLowerCase(); return { ...record, score: terms.reduce((sum, term) => sum + (text.includes(term) ? 1 : 0), 0) }; }).filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map(({ extractedText, ...item }) => ({ ...item, excerpt: String(extractedText || "").slice(0, 600) }));
}

export function registerGoogleAutomationRoutes(app: Express, dependencies: Dependencies) {
  const { state, saveState, audit, getDayPlan } = dependencies;
  state.googleSyncServices ||= Object.fromEntries(SERVICES.map(service => [service, { service, state: "never", attempts: 0 }]));
  state.googleSyncRuns ||= []; state.googleEmailReviews ||= []; state.googleEmailRules ||= []; state.googleCalendarOwnership ||= []; state.googleDriveIndex ||= [];
  let running: Promise<any> | null = null;

  const serviceStatus = () => ({ connected: Boolean(state.vault?.googleRefreshToken), intervalMinutes: 15, services: state.googleSyncServices, attentionCount: SERVICES.filter(service => state.googleSyncServices[service]?.state === "failed").length + (state.googleActionProposals || []).filter((item: any) => item.status === "pending").length, lastRuns: (state.googleSyncRuns || []).slice(0, 50) });
  const sync = async (trigger: "startup" | "scheduled" | "manual") => {
    if (running) return running;
    running = (async () => {
      const run: any = { id: id("gsync"), trigger, startedAt: nowIso(), services: {} }; state.googleSyncRuns.unshift(run);
      let accessToken: string;
      try { accessToken = await token(state); } catch (error: any) { for (const service of SERVICES) state.googleSyncServices[service] = { ...state.googleSyncServices[service], state: "failed", lastError: error.message, retryAt: nextRetry((state.googleSyncServices[service]?.attempts || 0) + 1), attempts: (state.googleSyncServices[service]?.attempts || 0) + 1 }; run.finishedAt = nowIso(); run.status = "failed"; await saveState(); throw error; }
      const workspace = state.googleWorkspace || { account: null, calendarEvents: [], gmailMessages: [], driveFiles: [] };
      const execute = async (service: Service, operation: () => Promise<any>) => { const started = Date.now(); try { const result = await operation(); state.googleSyncServices[service] = { service, state: "healthy", cursor: result.cursor || state.googleSyncServices[service]?.cursor || null, lastSuccessAt: nowIso(), latencyMs: Date.now() - started, lastError: null, retryAt: null, attempts: 0 }; run.services[service] = { status: "success", records: result.count, latencyMs: Date.now() - started }; return result; } catch (error: any) { const attempts = (state.googleSyncServices[service]?.attempts || 0) + 1; state.googleSyncServices[service] = { ...state.googleSyncServices[service], service, state: "failed", attempts, lastError: error.message, latencyMs: Date.now() - started, retryAt: nextRetry(attempts) }; run.services[service] = { status: "failed", message: error.message }; return null; } };
      const start = new Date(), end = new Date(start.getTime() + 60 * 86400000);
      const [calendar, gmail, drive] = await Promise.all([
        execute("calendar", async () => { const result = await get(`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=150&timeMin=${encodeURIComponent(start.toISOString())}&timeMax=${encodeURIComponent(end.toISOString())}`, accessToken); workspace.calendarEvents = (result.items || []).map((event: any) => ({ id: event.id, title: String(event.summary || "Untitled event").slice(0, 500), start: event.start?.dateTime || event.start?.date, end: event.end?.dateTime || event.end?.date, status: event.status, htmlLink: event.htmlLink, owned: Boolean(event.extendedProperties?.private?.lifeosOwned), sourceKey: event.extendedProperties?.private?.lifeosSourceKey || null })); return { count: workspace.calendarEvents.length, cursor: result.nextSyncToken }; }),
        execute("gmail", async () => { const list = await get("https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=50&q=newer_than%3A45d%20in%3Ainbox%20(is%3Aimportant%20OR%20is%3Astarred%20OR%20is%3Aunread)", accessToken), messages: any[] = []; for (let offset = 0; offset < (list.messages || []).length; offset += 3) messages.push(...await Promise.all(list.messages.slice(offset, offset + 3).map(async (item: any) => { const message = await get(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`, accessToken), labels = message.labelIds || [], candidate = { id: message.id, threadId: message.threadId, from: header(message, "From").slice(0, 300), subject: header(message, "Subject").slice(0, 500), date: header(message, "Date").slice(0, 100), labelIds: labels, unread: labels.includes("UNREAD"), snippet: String(message.snippet || "").slice(0, 240) }; return { ...candidate, reasonSelected: emailSelectionReason(candidate, state.googleEmailRules) }; }))); workspace.gmailMessages = messages.filter(item => item.reasonSelected); return { count: workspace.gmailMessages.length, cursor: list.resultSizeEstimate }; }),
        execute("drive", async () => { const result = await get("https://www.googleapis.com/drive/v3/files?pageSize=100&orderBy=modifiedTime%20desc&fields=files(id%2Cname%2CmimeType%2CmodifiedTime%2CwebViewLink%2Cdescription%2Cmd5Checksum%2Cversion)", accessToken); workspace.driveFiles = (result.files || []).map((file: any) => ({ id: file.id, name: file.name, mimeType: file.mimeType, modifiedTime: file.modifiedTime, webViewLink: file.webViewLink, description: file.description, checksum: file.md5Checksum, revision: file.version })); return { count: workspace.driveFiles.length, cursor: result.nextPageToken }; }),
      ]);
      workspace.lastSyncAt = nowIso(); workspace.counts = { calendarEvents: workspace.calendarEvents.length, gmailMessages: workspace.gmailMessages.length, driveFiles: workspace.driveFiles.length }; workspace.lastError = SERVICES.every(service => state.googleSyncServices[service].state === "failed") ? "All Google services failed." : null; state.googleWorkspace = workspace;
      run.finishedAt = nowIso(); run.status = SERVICES.some(service => state.googleSyncServices[service].state === "failed") ? "partial" : "success"; state.googleSyncRuns = state.googleSyncRuns.slice(0, 200); audit("google_automation_sync", { runId: run.id, trigger, status: run.status }); await saveState(); return { ...serviceStatus(), counts: workspace.counts, calendar, gmail, drive };
    })().finally(() => { running = null; });
    return running;
  };

  app.get("/api/google/services/status", (_req, res) => res.json(serviceStatus()));
  app.get("/api/google/sync-history", (_req, res) => res.json({ runs: (state.googleSyncRuns || []).slice(0, 100) }));
  app.post("/api/google/automation/sync", async (_req, res) => { try { res.json(await sync("manual")); } catch (error: any) { res.status(502).json(errorEnvelope("GOOGLE_SYNC_FAILED", error.message, "Reconnect Google if the grant was revoked, then retry.")); } });

  app.get("/api/google/inbox", (req, res) => { const reviewed = new Map((state.googleEmailReviews || []).map((item: any) => [item.messageId, item])); const records = (state.googleWorkspace?.gmailMessages || []).map((item: any) => ({ ...item, review: reviewed.get(item.id) || null })); res.json({ records, count: records.length, privacy: "Message bodies are fetched only when Analyse message is selected and are never retained." }); });
  app.post("/api/google/inbox/:id/analyse", async (req, res) => { try { const metadata = (state.googleWorkspace?.gmailMessages || []).find((item: any) => item.id === req.params.id); if (!metadata) return res.status(404).json(errorEnvelope("EMAIL_NOT_FOUND", "This message is not in the important-email index.")); const accessToken = await token(state), message = await get(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(req.params.id)}?format=full`, accessToken), text = strip(bodyText(message)).slice(0, 12000), sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean), summary = sentences.slice(0, 3).join(" ").slice(0, 900) || metadata.snippet || "No readable message text was available."; const review = { id: id("emailreview"), messageId: metadata.id, threadId: metadata.threadId, sender: metadata.from, subject: metadata.subject, receivedAt: metadata.date, reasonSelected: metadata.reasonSelected, summary, reviewedAt: nowIso(), reviewState: "analysed", sourceLink: `https://mail.google.com/mail/u/0/#inbox/${metadata.id}` }; state.googleEmailReviews = [review, ...(state.googleEmailReviews || []).filter((item: any) => item.messageId !== metadata.id)].slice(0, 500); audit("google_email_analysed", { messageId: metadata.id, bodyRetained: false }); await saveState(); res.json(review); } catch (error: any) { res.status(502).json(errorEnvelope("EMAIL_ANALYSIS_FAILED", error.message, "Retry after the Gmail service is healthy.")); } });
  app.post("/api/google/inbox/:id/proposals", async (req, res) => { const review = (state.googleEmailReviews || []).find((item: any) => item.messageId === req.params.id); if (!review) return res.status(409).json(errorEnvelope("EMAIL_ANALYSIS_REQUIRED", "Analyse this message before preparing an action.")); const allowed = ["task", "calendar", "business-lead", "ignore-rule"], kind = String(req.body.kind || "task"); if (!allowed.includes(kind)) return res.status(400).json(errorEnvelope("INVALID_EMAIL_ACTION", "Choose task, calendar, business-lead, or ignore-rule.")); const proposal = { id: id("google"), type: `email-${kind}`, title: `${kind === "task" ? "Create task from" : kind === "calendar" ? "Create commitment from" : kind === "business-lead" ? "Save business lead from" : "Ignore similar email from"} ${review.subject}`, summary: review.summary, preview: [review.sender, review.subject], payload: { reviewId: review.id, title: review.subject, dueDate: req.body.dueDate || null, sender: review.sender }, status: "pending", createdAt: nowIso() }; state.googleActionProposals = [proposal, ...(state.googleActionProposals || [])].slice(0, 200); await saveState(); res.status(201).json(proposal); });

  app.post("/api/google/calendar/reconcile-preview", async (req, res) => { const startDate = /^\d{4}-\d{2}-\d{2}$/.test(String(req.body.startDate || "")) ? String(req.body.startDate) : nowIso().slice(0, 10), range = ["day", "shift-cycle", "seven-days"].includes(req.body.range) ? req.body.range : "day", days = range === "seven-days" ? 7 : range === "shift-cycle" ? 4 : 1, desired: any[] = []; for (let offset = 0; offset < days; offset++) { const date = new Date(`${startDate}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + offset); const day = date.toISOString().slice(0, 10), plan = getDayPlan(day); for (const [index, block] of (plan.blocks || []).entries()) { if (["sleep", "work", "commute"].includes(block.category)) continue; const sourceKey = `${day}:${block.sourceId || block.category}:${index}`; desired.push({ sourceKey, fingerprint: calendarFingerprint(sourceKey), planDate: day, planVersion: 1, title: `LifeOS · ${block.title}`, start: `${day}T${block.start}:00+02:00`, end: `${block.end === "24:00" ? new Date(date.getTime() + 86400000).toISOString().slice(0, 10) : day}T${block.end === "24:00" ? "00:00" : block.end}:00+02:00`, category: block.category }); } } const existing = (state.googleWorkspace?.calendarEvents || []).filter((item: any) => String(item.start) >= `${startDate}T00:00`).map((item: any) => ({ ...item, owned: Boolean(item.owned || item.sourceKey) })), diff = reconcileCalendar(desired, existing); const proposal = { id: id("google"), type: "calendar-reconciliation", title: `Reconcile ${range.replace("-", " ")} from ${startDate}`, summary: `${diff.creates.length} creates, ${diff.updates.length} updates, ${diff.removals.length} removals, ${diff.conflicts.length} conflicts.`, preview: [...diff.creates.map(item => `Create ${item.start.slice(11,16)} ${item.title}`), ...diff.updates.map(item => `Update ${item.after.title}`), ...diff.removals.map(item => `Remove ${item.title}`)], payload: { startDate, range, diff }, status: "pending", createdAt: nowIso() }; state.googleActionProposals = [proposal, ...(state.googleActionProposals || []).filter((item: any) => item.status !== "pending" || item.type !== proposal.type)].slice(0, 200); await saveState(); res.status(201).json(proposal); });

  app.get("/api/google/drive/workspace", (_req, res) => { const resources = (state.googleActionProposals || []).filter((item: any) => item.status === "applied").flatMap((item: any) => item.result || []).filter((item: any) => item.link); res.json({ name: "43v3r Technology · LifeOS", folders: ["Business Plan", "Product", "Customer Research", "Roadmaps", "Finance", "Releases", "Archive"], resources, index: (state.googleDriveIndex || []).map(({ extractedText, ...item }: any) => item) }); });
  app.post("/api/google/drive/structure-proposal", async (_req, res) => { const parent = (state.googleActionProposals || []).filter((item: any) => item.status === "applied").flatMap((item: any) => item.result || []).find((item: any) => item.name === "43v3r Technology · LifeOS"); if (!parent) return res.status(409).json(errorEnvelope("DRIVE_WORKSPACE_MISSING", "Create the 43v3r Drive workspace first.")); const folders = ["Business Plan", "Product", "Customer Research", "Roadmaps", "Finance", "Releases", "Archive"], proposal = { id: id("google"), type: "create-drive-structure", title: "Create managed Drive subfolders", summary: `Creates ${folders.length} folders inside the existing LifeOS workspace.`, preview: folders, payload: { parentId: parent.id, folders }, status: "pending", createdAt: nowIso() }; state.googleActionProposals = [proposal, ...(state.googleActionProposals || [])]; await saveState(); res.status(201).json(proposal); });
  app.post("/api/google/drive/upload-proposal", async (req, res) => { const name = String(req.body.name || "").trim(), mimeType = String(req.body.mimeType || "application/octet-stream"), dataBase64 = String(req.body.dataBase64 || "").replace(/^data:[^,]+,/, ""); if (!name || !dataBase64) return res.status(400).json(errorEnvelope("INVALID_DRIVE_UPLOAD", "Choose a named file to upload.", "Files are limited to 5 MB in this local workflow.")); if (Buffer.byteLength(dataBase64, "base64") > 5 * 1024 * 1024) return res.status(413).json(errorEnvelope("DRIVE_UPLOAD_TOO_LARGE", "The selected file exceeds the 5 MB upload limit.")); const parent = (state.googleActionProposals || []).filter((item: any) => item.status === "applied").flatMap((item: any) => item.result || []).find((item: any) => item.name === "43v3r Technology · LifeOS"); if (!parent) return res.status(409).json(errorEnvelope("DRIVE_WORKSPACE_MISSING", "Create the LifeOS Drive workspace first.")); const proposal = { id: id("google"), type: "upload-drive-file", title: `Upload ${name} to Drive`, summary: "The file will be uploaded only after approval and then becomes eligible for indexing.", preview: [name, mimeType, `${Buffer.byteLength(dataBase64,"base64")} bytes`], payload: { parentId: parent.id, name, mimeType, dataBase64 }, status: "pending", createdAt: nowIso() }; state.googleActionProposals = [proposal, ...(state.googleActionProposals || [])]; await saveState(); res.status(201).json({ ...proposal, payload: undefined }); });
  app.get("/api/google/drive/index", (_req, res) => res.json({ records: (state.googleDriveIndex || []).map(({ extractedText, ...item }: any) => item) }));
  app.get("/api/google/drive/search", (req, res) => res.json({ query: String(req.query.q || ""), results: searchDriveIndex(state.googleDriveIndex || [], String(req.query.q || "")), synchronizedAt: state.googleWorkspace?.lastSyncAt || null }));
  app.post("/api/google/drive/index/:fileId", async (req, res) => { try { const file = (state.googleWorkspace?.driveFiles || []).find((item: any) => item.id === req.params.fileId); if (!file) return res.status(404).json(errorEnvelope("DRIVE_FILE_NOT_FOUND", "The selected file is not in the synchronized Drive metadata.")); const managed = String(file.description || "").toLowerCase().includes("lifeos") || (state.googleActionProposals || []).some((proposal: any) => (proposal.result || []).some((item: any) => item.id === file.id)); if (!managed) return res.status(403).json(errorEnvelope("DRIVE_FILE_NOT_MANAGED", "Only LifeOS-created or explicitly uploaded files can be indexed.")); const accessToken = await token(state); let url = `https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`, extractionStatus = "indexed"; if (file.mimeType === "application/vnd.google-apps.document") url = `https://www.googleapis.com/drive/v3/files/${file.id}/export?mimeType=text%2Fplain`; else if (file.mimeType === "application/vnd.google-apps.spreadsheet") url = `https://www.googleapis.com/drive/v3/files/${file.id}/export?mimeType=text%2Fcsv`; else if (!/text|markdown|csv|json/.test(file.mimeType || "")) extractionStatus = "unsupported"; let extractedText = ""; if (extractionStatus === "indexed") { const response = await fetch(url, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) throw new Error(`Drive extraction failed (${response.status}).`); extractedText = (await response.text()).slice(0, 200000); } const record = { id: `driveindex_${file.id}`, fileId: file.id, name: file.name, mimeType: file.mimeType, revision: file.revision || null, checksum: file.checksum || hash(extractedText), sourceLink: file.webViewLink, extractionStatus, indexedAt: nowIso(), accessStatus: "available", extractedText }; state.googleDriveIndex = [record, ...(state.googleDriveIndex || []).filter((item: any) => item.fileId !== file.id)]; await saveState(); res.json({ ...record, extractedText: undefined }); } catch (error: any) { res.status(502).json(errorEnvelope("DRIVE_INDEX_FAILED", error.message, "Confirm the file still exists and retry indexing.")); } });

  const timer = setInterval(() => { if (state.vault?.googleRefreshToken) void sync("scheduled").catch(() => undefined); }, 15 * 60_000); timer.unref();
  if (state.vault?.googleRefreshToken && process.env.NODE_ENV !== "test") setTimeout(() => void sync("startup").catch(() => undefined), 1500).unref();
}
