import React,{useEffect,useState} from "react";
import { CheckCircle2, ChevronDown, Sparkles, X } from "lucide-react";
const label=(v:string)=>v.replaceAll("_"," ");
export default function AiActionCenter({onActivity}:{onActivity:(message:string)=>void}){
 const [actions,setActions]=useState<any[]>([]),[request,setRequest]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch("/api/ai/actions?status=pending");if(r.ok)setActions(await r.json())};useEffect(()=>{load()},[]);
 const errorMessage=(value:any)=>value?.error?.message||value?.error||value?.message||"LifeOS could not complete that action.";
 const propose=async(e:React.FormEvent)=>{e.preventDefault();if(request.trim().length<5)return;setBusy(true);try{const r=await fetch("/api/ai/actions/propose",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request})});const x=await r.json();if(!r.ok)throw new Error(errorMessage(x));setRequest("");onActivity(`AI prepared ${x.actions.length} controlled action proposal${x.actions.length===1?"":"s"}.`);await load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 const decide=async(id:string,decision:"approve"|"reject")=>{setBusy(true);try{const r=await fetch(`/api/ai/actions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});const x=await r.json();if(!r.ok)throw new Error(errorMessage(x));onActivity(decision==="approve"?"Approved and saved an AI-proposed LifeOS change.":"Rejected an AI proposal.");await load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 return <details className="border-b bg-purple-50/60"><summary className="flex cursor-pointer list-none items-center justify-between px-5 py-3"><span className="flex items-center gap-2 text-xs font-bold text-purple-900"><Sparkles className="h-4 w-4"/>Controlled AI actions <span className="rounded-full bg-purple-200 px-2 py-0.5 text-[9px]">{actions.length} pending</span></span><ChevronDown className="h-4 w-4 text-purple-500"/></summary><div className="border-t border-purple-100 p-4"><form onSubmit={propose} className="flex gap-2"><input value={request} onChange={e=>setRequest(e.target.value)} placeholder="Example: create three tasks to prepare for my next night shifts" className="min-w-0 flex-1 rounded-lg border border-purple-200 px-3 py-2 text-xs"/><button disabled={busy||request.trim().length<5} className="rounded-lg bg-purple-700 px-3 text-xs font-bold text-white disabled:opacity-40">Prepare</button></form><p className="mt-2 text-[9px] text-purple-700">AI can prepare tasks, work tasks, shifts, goal updates and habits. Nothing is saved until you approve each proposal.</p>{actions.length>0&&<div className="mt-3 grid gap-2 md:grid-cols-2">{actions.map(a=><article key={a.id} className="rounded-xl border border-purple-100 bg-white p-3"><div className="flex justify-between gap-2"><div><span className="text-[9px] uppercase text-purple-600">{label(a.type)}</span><strong className="block text-xs">{a.title}</strong></div><span className="text-[9px] text-stone-400">{a.provider||"LifeOS"}</span></div><p className="mt-2 text-[10px] leading-4 text-stone-600">{a.explanation}</p>{a.contextSnapshot&&<p className="mt-2 text-[9px] text-blue-700">Grounded in {a.contextSnapshot.domains.join(", ")} · {new Date(a.contextSnapshot.generatedAt).toLocaleString()}</p>}<details className="mt-2"><summary className="cursor-pointer text-[9px] text-stone-500">Preview exact fields</summary><pre className="mt-1 max-h-32 overflow-auto rounded bg-stone-50 p-2 text-[9px] whitespace-pre-wrap">{JSON.stringify(a.payload,null,2)}</pre></details><div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>decide(a.id,"approve")} className="flex items-center gap-1 rounded-lg bg-emerald-700 px-3 py-1.5 text-[10px] font-bold text-white"><CheckCircle2 className="h-3 w-3"/>Approve</button><button disabled={busy} onClick={()=>decide(a.id,"reject")} className="flex items-center gap-1 rounded-lg border border-red-200 px-3 py-1.5 text-[10px] font-bold text-red-700"><X className="h-3 w-3"/>Reject</button></div></article>)}</div>}</div></details>
}
