import React,{useEffect,useMemo,useState} from "react";
import { BookOpen, Building2, CheckCircle2, ChevronRight, Code2, ExternalLink, GraduationCap, Plus, RefreshCw, ShieldCheck, Sparkles, TestTube2 } from "lucide-react";
import { Badge, MetricCard, Notice, SegmentedTabs } from "../ui/primitives";
import { notifyLifeOs } from "../ui/feedback";

const input="w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm";
const stageLabels:Record<string,string>={generated:"Generated",reviewed:"Reviewed",tested:"Tested",explained:"Explained",owned:"Owned"};

export default function CodebaseBusinessView({existingTasks,onSaved,onActivity,onAsk}:{existingTasks:any[];onSaved:()=>Promise<void>;onActivity:(message:string)=>void;onAsk:()=>void}){
 const[data,setData]=useState<any>(null),[learning,setLearning]=useState<any>(null),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(""),[view,setView]=useState("coach"),[answers,setAnswers]=useState<Record<number,number>>({}),[check,setCheck]=useState<any>(null),[notes,setNotes]=useState(""),[confidence,setConfidence]=useState(0);
 const load=async()=>{const [guideResponse,learningResponse]=await Promise.all([fetch("/api/business/codebase"),fetch("/api/business/code-learning")]);if(guideResponse.ok)setData(await guideResponse.json());if(learningResponse.ok){const result=await learningResponse.json();setLearning(result);if(!detail&&result.records[0])await selectFeature(result.records[0].feature.id)}};
 const selectFeature=async(id:string)=>{setBusy("feature");try{const response=await fetch(`/api/business/code-learning/${id}`),result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Feature guide could not be loaded.");setDetail(result);setNotes(result.record.notes||"");setConfidence(result.record.confidence||0);setAnswers({});setCheck(null)}catch(error:any){notifyLifeOs(error.message,"danger")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 const addTask=async(item:any)=>{setBusy(String(item.order));try{const title=`Codebase learning ${item.order}: ${item.title}`;const response=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,goalId:"goal_43v3r",projectId:"project_43v3r",priority:item.order<=2?"High":"Medium",deepWork:item.order!==3,energyLevel:item.order<=2?"High":"Medium",estimatedTime:item.order===1?90:60,contextTags:["business","codebase","product-development"],notes:item.outcome})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||result?.error||"Task could not be created");onActivity(`Business-development task created: ${title}`);await onSaved()}catch(error:any){notifyLifeOs(error.message,"danger")}finally{setBusy("")}};
 const updateLearning=async(body:any)=>{if(!detail)return;setBusy("save");try{const response=await fetch(`/api/business/code-learning/${detail.feature.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Learning progress could not be saved.");notifyLifeOs("Code understanding progress saved.","success");onActivity(`${detail.feature.title}: ${stageLabels[result.stage]}.`);await selectFeature(detail.feature.id);const overview=await fetch("/api/business/code-learning").then(r=>r.json());setLearning(overview)}catch(error:any){notifyLifeOs(error.message,"danger")}finally{setBusy("")}};
 const submitCheck=async()=>{if(!detail)return;setBusy("check");try{const ordered=detail.feature.questions.map((_:any,index:number)=>answers[index]);const response=await fetch(`/api/business/code-learning/${detail.feature.id}/check`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers:ordered})}),result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Knowledge check could not be completed.");setCheck(result);notifyLifeOs(`Knowledge check: ${result.score}%` ,result.passed?"success":"warning");await selectFeature(detail.feature.id);setCheck(result)}catch(error:any){notifyLifeOs(error.message,"danger")}finally{setBusy("")}};
 const nextStage=useMemo(()=>{if(!detail)return null;const stages=detail.stages||[],index=stages.indexOf(detail.record.stage);return stages[index+1]||null},[detail]);
 if(!data||!learning)return <div className="rounded-2xl border p-8 text-center text-sm text-stone-500">Loading the LifeOS code understanding coach…</div>;
 return <div className="space-y-4">
  <section className="rounded-2xl bg-stone-900 p-5 text-white"><div className="flex items-center gap-2"><Code2 className="h-5 w-5 text-emerald-400"/><h2 className="font-bold">Understand LifeOS, do not merely generate it</h2></div><p className="mt-2 max-w-3xl text-sm text-stone-300">AI can help you build faster, but LifeOS now tracks whether you reviewed, tested, explained, and genuinely own each important code path.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={onAsk} className="rounded-lg bg-emerald-400 px-4 py-2 text-xs font-bold text-stone-950">Ask AI to explain this code</button><Badge tone="ai">Teach before changing</Badge></div></section>
  <SegmentedTabs label="Codebase workspace" items={[{id:"coach",label:"Understanding coach"},{id:"architecture",label:"Architecture"},{id:"learning",label:"Learning path"},{id:"business",label:"Business evidence"}]} value={view} onChange={setView}/>
  {view==="coach"&&<Coach learning={learning} detail={detail} busy={busy} answers={answers} setAnswers={setAnswers} check={check} notes={notes} setNotes={setNotes} confidence={confidence} setConfidence={setConfidence} nextStage={nextStage} onSelect={selectFeature} onSave={()=>updateLearning({notes,confidence})} onStage={(stage:string)=>updateLearning({stage,notes,confidence})} onCheck={submitCheck}/>}
  {view==="architecture"&&<><section className="grid grid-cols-2 gap-2 md:grid-cols-5">{Object.entries(data.metrics).map(([key,value])=><div key={key} className="rounded-xl border p-3"><span className="text-[9px] uppercase text-stone-500">{key.replaceAll(/([A-Z])/g," $1")}</span><strong className="mt-1 block text-sm">{typeof value==="boolean"?(value?"Available":"Missing"):String(value)}</strong></div>)}</section><section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Building2 className="h-4 w-4 text-blue-700"/>How the system fits together</h3><div className="mt-3 grid gap-2 lg:grid-cols-2">{data.architecture.map((item:any)=><details key={item.id} className="rounded-xl border p-3"><summary className="cursor-pointer text-sm font-semibold">{item.name} <span className="ml-2 text-[10px] font-normal text-stone-400">{item.location}</span></summary><p className="mt-2 text-xs leading-5 text-stone-600">{item.purpose}</p><p className="mt-2 rounded-lg bg-blue-50 p-2 text-xs text-blue-900"><strong>Business lesson:</strong> {item.businessLesson}</p></details>)}</div></section></>}
  {view==="learning"&&<section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><BookOpen className="h-4 w-4 text-purple-700"/>Learning path</h3><p className="mt-1 text-xs text-stone-500">Add a structured lesson to Plan. Every task links learning to Build 43v3r Technology.</p><div className="mt-3 space-y-2">{data.learningPath.map((item:any)=>{const title=`Codebase learning ${item.order}: ${item.title}`,exists=existingTasks.some(task=>task.title===title&&task.status!=="completed");return <div key={item.order} className="flex gap-3 rounded-xl border p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-purple-100 text-xs font-bold text-purple-800">{item.order}</span><div className="min-w-0 flex-1"><strong className="text-sm">{item.title}</strong><p className="mt-1 text-xs leading-5 text-stone-500">{item.outcome}</p></div><button disabled={exists||busy===String(item.order)} onClick={()=>void addTask(item)} className="h-8 shrink-0 rounded-lg border px-2 text-[10px] font-bold disabled:opacity-40">{exists?<><CheckCircle2 className="mr-1 inline h-3 w-3"/>Added</>:busy===String(item.order)?<RefreshCw className="h-3 w-3 animate-spin"/>:<><Plus className="mr-1 inline h-3 w-3"/>Add task</>}</button></div>})}</div></section>}
  {view==="business"&&<div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border p-4"><h3 className="font-semibold">Business opportunities to validate</h3><div className="mt-3 space-y-2">{data.businessDevelopment.opportunities.map((item:string)=><div key={item} className="rounded-lg bg-emerald-50 p-3 text-xs text-emerald-950"><ExternalLink className="mr-2 inline h-3.5 w-3.5"/>{item}</div>)}</div></section><section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-emerald-700"/>Evidence rules</h3><ul className="mt-3 space-y-2">{data.businessDevelopment.guardrails.map((item:string)=><li key={item} className="text-xs leading-5 text-stone-600">• {item}</li>)}</ul><div className="mt-4 rounded-lg bg-stone-100 p-3 text-xs"><strong>43v3r progress:</strong> {data.businessDevelopment.taskCounts.completed} of {data.businessDevelopment.taskCounts.total} linked tasks completed.</div></section></div>}
 </div>
}

function Coach({learning,detail,busy,answers,setAnswers,check,notes,setNotes,confidence,setConfidence,nextStage,onSelect,onSave,onStage,onCheck}:any){
 return <div className="space-y-4">
  <Notice tone="authoritative" title="Understanding is tracked separately from build quality">A successful test or build does not mean you understand the code. “Owned” requires ordered review, testing, explanation, a passed knowledge check, and at least 70% confidence.</Notice>
  <div className="grid grid-cols-2 gap-2 md:grid-cols-5"><MetricCard label="Reviewed" value={`${learning.summary.reviewed}/${learning.summary.total}`}/><MetricCard label="Tested" value={`${learning.summary.tested}/${learning.summary.total}`}/><MetricCard label="Explained" value={`${learning.summary.explained}/${learning.summary.total}`}/><MetricCard label="Owned" value={`${learning.summary.owned}/${learning.summary.total}`}/><MetricCard label="Confidence" value={`${learning.summary.averageConfidence}%`}/></div>
  <div className="grid gap-4 xl:grid-cols-[300px_1fr]">
   <section className="h-fit rounded-2xl border p-3"><h3 className="px-2 py-1 text-sm font-semibold">Core LifeOS lessons</h3><div className="mt-2 space-y-1">{learning.records.map((record:any)=><button key={record.feature.id} onClick={()=>onSelect(record.feature.id)} className={`w-full rounded-xl border p-3 text-left ${detail?.feature.id===record.feature.id?"border-violet-300 bg-violet-50":"bg-white"}`}><div className="flex justify-between gap-2"><strong className="text-xs">{record.feature.title}</strong><ChevronRight className="h-3.5 w-3.5 shrink-0"/></div><div className="mt-2 flex items-center justify-between"><Badge tone={record.stage==="owned"?"success":record.stage==="generated"?"warning":"ai"}>{stageLabels[record.stage]}</Badge><span className="text-[10px] text-stone-400">{record.confidence||0}% confidence</span></div></button>)}</div></section>
   {detail&&<section className="space-y-4 rounded-2xl border p-4">
    <div><span className="life-eyebrow">{detail.feature.durationMinutes} minute guided lesson</span><h3 className="mt-1 text-lg font-semibold">{detail.feature.title}</h3><p className="mt-1 text-sm leading-6 text-stone-600">{detail.feature.problem}</p><div className="mt-2 flex flex-wrap gap-1">{detail.feature.concepts.map((concept:string)=><Badge key={concept}>{concept}</Badge>)}</div></div>
    <div><h4 className="text-xs font-bold uppercase tracking-wide text-stone-500">Feature trace</h4><div className="mt-2 space-y-2">{detail.feature.flow.map((step:any,index:number)=><div key={step.file} className="grid gap-2 rounded-xl bg-stone-50 p-3 sm:grid-cols-[28px_100px_1fr]"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-stone-900 text-[10px] font-bold text-white">{index+1}</span><div><strong className="text-xs">{step.layer}</strong><code className="mt-1 block break-all text-[9px] text-violet-700">{step.file}</code></div><p className="text-xs leading-5 text-stone-600">{step.explanation}</p></div>)}</div></div>
    <div className="grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-red-50 p-3"><h4 className="text-xs font-bold text-red-900">What can go wrong</h4><ul className="mt-2 space-y-1">{detail.feature.risks.map((risk:string)=><li key={risk} className="text-xs text-red-800">• {risk}</li>)}</ul></div><div className="rounded-xl bg-blue-50 p-3"><h4 className="text-xs font-bold text-blue-900">Explain it in your own words</h4><textarea value={notes} onChange={event=>setNotes(event.target.value)} className={`${input} mt-2 min-h-24`} placeholder="What problem does this solve? How does data move? What would you inspect first if it failed?"/><label className="mt-2 block text-[10px] font-bold text-blue-900">Confidence: {confidence}%</label><input type="range" min="0" max="100" step="5" value={confidence} onChange={event=>setConfidence(Number(event.target.value))} className="mt-1 w-full"/></div></div>
    <div className="flex flex-wrap gap-2"><button disabled={busy==="save"} onClick={onSave} className="life-button-secondary">Save notes</button>{nextStage&&<button disabled={busy==="save"} onClick={()=>onStage(nextStage)} className="life-button-primary">{nextStage==="tested"?<TestTube2 className="mr-1 inline h-3.5 w-3.5"/>:nextStage==="explained"?<GraduationCap className="mr-1 inline h-3.5 w-3.5"/>:<CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>}Mark {stageLabels[nextStage]}</button>}<Badge tone="authoritative">Current: {stageLabels[detail.record.stage]}</Badge></div>
    <div className="border-t pt-4"><h4 className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-violet-700"/>Knowledge check</h4><p className="mt-1 text-xs text-stone-500">Pass at 80% or higher. Wrong answers include explanations so this remains a teaching tool.</p><div className="mt-3 space-y-3">{detail.feature.questions.map((question:any,index:number)=><fieldset key={question.prompt} className="rounded-xl border p-3"><legend className="px-1 text-xs font-semibold">{index+1}. {question.prompt}</legend><div className="mt-2 space-y-1">{question.options.map((option:string,optionIndex:number)=><label key={option} className="flex cursor-pointer gap-2 rounded-lg p-2 text-xs hover:bg-stone-50"><input type="radio" name={`question-${index}`} checked={answers[index]===optionIndex} onChange={()=>setAnswers({...answers,[index]:optionIndex})}/>{option}</label>)}</div>{check?.results?.[index]&&<p className={`mt-2 rounded-lg p-2 text-xs ${check.results[index].correct?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-950"}`}>{check.results[index].correct?"Correct. ":"Review: "}{check.results[index].explanation}</p>}</fieldset>)}</div><button disabled={busy==="check"} onClick={onCheck} className="life-button-primary mt-3">{busy==="check"?"Checking…":"Submit knowledge check"}</button>{check&&<strong className={`ml-3 text-sm ${check.passed?"text-emerald-700":"text-amber-700"}`}>{check.score}% · {check.passed?"Passed":"Review and retry"}</strong>}</div>
   </section>}
  </div>
 </div>
}
