import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Banknote, CheckCircle2, Circle, Clock3, Flame, RefreshCw, Sparkles, Target, WalletCards } from "lucide-react";
import MarkdownMessage from "./MarkdownMessage";

const today = () => new Date().toISOString().slice(0, 10);
const zar = (value:number) => new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(value||0);

export default function ExecutiveAlignmentDashboard({ goals, tasks, intelligence, onNavigate, onToggleTask }: { goals:any[]; tasks:any[]; intelligence:any; onNavigate:(tab:string)=>void; onToggleTask:(id:string,status:string)=>void }) {
  const [integrations,setIntegrations]=useState<any>({command:null,context:null,projects:[],habits:[],focus:[],analytics:null,reviews:[]});
  const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const paths=["personal/command-center","ai/life-context","projects","habits","focus","planning/analytics","planning/reviews"];const values=await Promise.all(paths.map(async path=>{const response=await fetch(`/api/${path}`);return response.ok?response.json():null;}));setIntegrations({command:values[0],context:values[1],projects:values[2]||[],habits:values[3]||[],focus:values[4]||[],analytics:values[5],reviews:values[6]||[]});}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const date=today(), activeGoals=goals.filter(g=>!["completed","archived","cancelled"].includes(String(g.status).toLowerCase()));
  const openTasks=tasks.filter(t=>t.status!=="completed"),completed=tasks.filter(t=>t.status==="completed"),overdue=openTasks.filter(t=>t.dueDate&&t.dueDate<date);
  const dueTasks=useMemo(()=>[...openTasks].sort((a,b)=>String(a.dueDate||"9999").localeCompare(String(b.dueDate||"9999"))).slice(0,5),[tasks]);
  const goalIntel=new Map((intelligence?.goals||[]).map((item:any)=>[item.id,item]));
  const command=integrations.command||{},finance=command.finance||{},context=integrations.context||{};
  const habitsDone=integrations.habits.filter((h:any)=>(h.logs||[]).includes(date)).length;
  const activeFocus=integrations.focus.find((f:any)=>f.active),latestReview=integrations.reviews[0];
  const alerts=[...(command.alerts||[]),...overdue.map((t:any)=>({id:`task-${t.id}`,priority:"high",title:`Task overdue: ${t.title}`,description:`Due ${t.dueDate}`}))].slice(0,5);
  return <div className="space-y-4">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">LifeOS command dashboard</h2><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">LIVE DATA</span></div><p className="mt-1 text-xs text-stone-500">Goals, execution, routines, focus, finance, work and AI memory in one view.</p></div><button onClick={load} disabled={loading} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw className={`h-3.5 w-3.5 ${loading?"animate-spin":""}`}/>Refresh all</button></header>

    <section className="rounded-2xl bg-stone-900 p-4 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-400">Today’s integrated briefing</p><h3 className="mt-1 font-semibold">{command.briefing?.title||"Loading your saved operating picture…"}</h3><p className="mt-2 max-w-3xl text-xs leading-5 text-stone-300">{command.briefing?.summary||"LifeOS is combining your current records."}</p></div><div className="rounded-xl bg-white/10 px-4 py-3"><span className="text-[9px] uppercase text-stone-400">Next best action</span><strong className="mt-1 block max-w-xs text-sm">{command.briefing?.nextAction||dueTasks[0]?.title||"Review today’s priorities"}</strong></div></div></section>

    <div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">
      <Metric label="Active goals" value={activeGoals.length} tone="purple"/><Metric label="Open tasks" value={openTasks.length} tone={overdue.length?"amber":"blue"}/><Metric label="Projects" value={integrations.projects.filter((p:any)=>p.status!=="Completed").length}/><Metric label="Habits today" value={`${habitsDone}/${integrations.habits.length}`} tone="green"/>
      <Metric label="Focus this week" value={`${integrations.analytics?.totalFocusMinutes||0}m`}/><Metric label="Bank cash" value={zar(finance.cash)} tone="green"/><Metric label="After commitments" value={zar(finance.projectedAfterCommitments)} tone={(finance.projectedAfterCommitments||0)<0?"red":"green"}/><Metric label="AI memories" value={context.memory?.active||0} tone="purple"/>
    </div>

    <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr_0.9fr]">
      <section className="overflow-hidden rounded-2xl border"><Head icon={Clock3} title="Execution queue" action="All tasks" onClick={()=>onNavigate("tasks")}/><div className="divide-y">{dueTasks.map((task:any)=>{const late=task.dueDate&&task.dueDate<date;return <div key={task.id} className="flex gap-3 p-3"><button onClick={()=>onToggleTask(task.id,task.status)} className="text-stone-400 hover:text-emerald-600"><Circle className="h-4 w-4"/></button><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{task.title}</p><p className={`mt-1 text-[10px] ${late?"text-red-700":"text-stone-500"}`}>{task.priority||"Medium"} · {task.estimatedTime||0}m · {late?"Overdue ":""}{task.dueDate||"Unscheduled"}</p></div></div>})}{!dueTasks.length&&<Empty text="All tasks complete."/>}</div></section>
      <section className="rounded-2xl border p-4"><div className="flex justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold"><Target className="h-4 w-4 text-purple-700"/>Goal alignment</h3><button onClick={()=>onNavigate("goals")} className="text-xs text-purple-700">Manage</button></div><div className="mt-3 space-y-3">{activeGoals.slice(0,4).map(goal=>{const item:any=goalIntel.get(goal.id),progress=item?.taskProgress||0;return <button key={goal.id} onClick={()=>onNavigate("goals")} className="block w-full text-left"><div className="flex justify-between gap-2 text-xs"><strong className="truncate">{goal.title}</strong><span>{progress}%</span></div><div className="mt-1.5 h-1.5 rounded bg-stone-100"><div className="h-full rounded bg-purple-600" style={{width:`${progress}%`}}/></div><p className="mt-1 text-[9px] text-stone-500">{item?.completedTasks||0}/{item?.tasks||0} linked tasks · {goal.targetDate||"No target date"}</p></button>})}{!activeGoals.length&&<Empty text="No active goals."/>}</div></section>
      <section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><WalletCards className="h-4 w-4 text-emerald-700"/>Financial position</h3><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="Income" value={zar(finance.income)}/><Mini label="Expenses" value={zar(finance.expenses)}/><Mini label="Paid commitments" value={zar(finance.payments)}/><Mini label="Still unpaid" value={zar(finance.unpaidCommitments)}/></div><div className="mt-3 rounded-xl bg-stone-50 p-3 text-xs"><div className="flex justify-between"><span>Recorded bank cash</span><strong>{zar(finance.cash)}</strong></div><div className="mt-2 flex justify-between"><span>Safe discretionary</span><strong className="text-emerald-700">{zar(finance.safeDiscretionary)}</strong></div><div className="mt-2 flex justify-between"><span>Safe debt overpayment</span><strong>{zar(finance.safeDebtOverpayment)}</strong></div></div>{command.freshness?.stale&&<p className="mt-2 text-[9px] text-amber-700">Balance freshness warning active.</p>}<p className="mt-2 text-[9px] text-stone-400">Open Finance for accounts, debts and statements.</p></section>
    </div>

    <div className="grid gap-4 lg:grid-cols-3">
      <section className="rounded-2xl border p-4"><div className="flex justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold"><Flame className="h-4 w-4 text-orange-600"/>Daily consistency</h3><button onClick={()=>onNavigate("habits")} className="text-xs text-orange-700">Habits</button></div><div className="mt-3 flex items-center gap-4"><div className="text-3xl font-bold">{habitsDone}<span className="text-sm text-stone-400">/{integrations.habits.length}</span></div><div className="text-xs text-stone-500">habits completed today<br/>{activeFocus?`Focus active: ${activeFocus.title}`:`${integrations.analytics?.totalFocusMinutes||0} recorded focus minutes`}</div></div><div className="mt-3 flex gap-2"><button onClick={()=>onNavigate("habits")} className="rounded-lg border px-3 py-2 text-xs font-bold">Log habits</button><button onClick={()=>onNavigate("focus")} className="rounded-lg border px-3 py-2 text-xs font-bold">Focus</button></div></section>
      <section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="h-4 w-4 text-amber-600"/>Attention centre <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[9px] text-amber-700">{alerts.length}</span></h3><div className="mt-3 space-y-2">{alerts.map((a:any)=><div key={a.id} className={`rounded-lg border p-2.5 ${a.priority==="high"?"border-red-100 bg-red-50":"border-amber-100 bg-amber-50"}`}><strong className="block text-xs">{a.title}</strong><p className="mt-1 line-clamp-2 text-[10px] text-stone-600">{a.description}</p></div>)}{!alerts.length&&<div className="py-6 text-center text-xs text-emerald-700"><CheckCircle2 className="mx-auto mb-2 h-5 w-5"/>No active alerts.</div>}</div></section>
      <section className="rounded-2xl border p-4"><div className="flex justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-purple-600"/>AI continuity</h3><button onClick={()=>onNavigate("reviews")} className="text-xs text-purple-700">Reviews</button></div>{latestReview?<div className="mt-3 max-h-48 overflow-auto text-xs"><p className="mb-2 text-[9px] uppercase text-stone-400">Latest {latestReview.type} review · {latestReview.provider}</p><MarkdownMessage content={latestReview.content}/></div>:<div className="mt-3 rounded-xl bg-stone-50 p-4 text-xs text-stone-500">No planning review saved yet. Generate one from Reviews using your real records.</div>}<div className="mt-3 flex justify-between text-[10px] text-stone-500"><span>{context.memory?.userConfirmed||0} user-confirmed memories</span><span>{command.actions?.length||0} pending AI actions</span></div></section>
    </div>
  </div>;
}

function Metric({label,value,tone="stone"}:{label:string,value:any,tone?:string}){const colors:any={purple:"text-purple-700",blue:"text-blue-700",green:"text-emerald-700",amber:"text-amber-700",red:"text-red-700",stone:"text-stone-900"};return <div className="rounded-xl border bg-stone-50 p-3"><span className="block text-[9px] uppercase text-stone-500">{label}</span><strong className={`mt-1 block truncate text-lg ${colors[tone]}`}>{value}</strong></div>}
function Mini({label,value}:{label:string,value:string}){return <div className="rounded-lg border p-2"><span className="block text-[9px] text-stone-500">{label}</span><strong className="text-xs">{value}</strong></div>}
function Head({icon:Icon,title,action,onClick}:any){return <div className="flex items-center justify-between border-b p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><Icon className="h-4 w-4 text-blue-700"/>{title}</h3><button onClick={onClick} className="flex items-center gap-1 text-xs text-blue-700">{action}<ArrowRight className="h-3 w-3"/></button></div>}
function Empty({text}:{text:string}){return <div className="p-5 text-center text-xs text-stone-500">{text}</div>}
