import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Cloud, FileSearch, History, Inbox, RefreshCw, Shield, TriangleAlert } from "lucide-react";
import GoogleBusinessPanel from "./GoogleBusinessPanel";

const TABS = ["Overview", "Important Email", "Calendar", "Drive Knowledge", "Tasks", "Sheets", "Contacts", "Proposals", "Sync History", "Privacy"] as const;
type Tab = typeof TABS[number];
const api = async (url: string, options?: RequestInit) => { const response = await fetch(url, options), result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || "Google Workspace request failed."); return result; };
const button = "life-button-secondary min-h-11";

export default function GoogleWorkspaceView() {
  const initial = new URLSearchParams(location.search).get("googleTab") as Tab | null;
  const [tab, setTabState] = useState<Tab>(TABS.includes(initial as Tab) ? initial! : "Overview"), [status, setStatus] = useState<any>(null), [services, setServices] = useState<any>(null), [inbox, setInbox] = useState<any[]>([]), [workspace, setWorkspace] = useState<any>(null), [query, setQuery] = useState(""), [results, setResults] = useState<any[]>([]), [busy, setBusy] = useState(""), [notice, setNotice] = useState("");
  const refresh = async () => { const [a,b,c,d] = await Promise.all([api("/api/google/status"),api("/api/google/services/status"),api("/api/google/inbox"),api("/api/google/drive/workspace")]); setStatus(a); setServices(b); setInbox(c.records || []); setWorkspace(d); };
  useEffect(() => { void refresh().catch(error => setNotice(error.message)); }, []);
  const setTab = (value: Tab) => { setTabState(value); const url = new URL(location.href); url.searchParams.set("googleTab", value); history.replaceState({}, "", url); };
  const act = async (name: string, url: string, method="POST", body:any={}) => { setBusy(name); setNotice(""); try { await api(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); setNotice("Saved. LifeOS refreshed the Google workspace state."); await refresh(); } catch(error:any){setNotice(error.message)} finally{setBusy("")} };
  const pending = status?.proposals || [], healthy = useMemo(() => ["calendar","gmail","drive"].filter(name=>(services?.services||{})[name]?.state === "healthy").length,[services]);
  const today = new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  if (!status) return <section className="life-card p-5"><RefreshCw className="h-5 w-5 animate-spin"/></section>;
  return <section className="life-card overflow-hidden">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-stone-200 p-5"><div><p className="text-[10px] font-bold uppercase tracking-widest text-blue-700">Automation workspace</p><h2 className="mt-1 text-xl font-semibold text-stone-900">Google Workspace</h2><p className="mt-1 text-xs text-stone-500">Important mail, conflict-safe planning, and approved Drive knowledge.</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${healthy===3?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{healthy}/3 services healthy</span><button className={button} disabled={!!busy||!status.connected} onClick={()=>act("sync","/api/google/automation/sync")}>{busy==="sync"?<RefreshCw className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>} Sync now</button></div></header>
    <nav className="flex gap-1 overflow-x-auto border-b border-stone-200 bg-stone-50 px-3 py-2" aria-label="Google Workspace sections">{TABS.map(item=><button key={item} onClick={()=>setTab(item)} className={`min-h-11 whitespace-nowrap rounded-lg px-3 text-xs font-semibold ${tab===item?"bg-white text-blue-800 shadow-sm":"text-stone-600 hover:bg-white"}`}>{item}{item==="Proposals"&&pending.length?` (${pending.length})`:""}</button>)}</nav>
    {notice&&<div role="status" className="mx-5 mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900">{notice}</div>}
    <div className="p-5">
      {tab==="Overview"&&<div className="grid gap-4 md:grid-cols-3">{(["calendar","gmail","drive"] as const).map(service=>{const item=services?.services?.[service]||{};return <article key={service} className="rounded-xl border border-stone-200 p-4"><div className="flex items-center justify-between"><strong className="capitalize">{service}</strong><span className={`h-2.5 w-2.5 rounded-full ${item.state==="healthy"?"bg-emerald-500":item.state==="failed"?"bg-red-500":"bg-stone-300"}`}/></div><p className="mt-3 text-xs text-stone-500">{item.lastSuccessAt?`Last success ${new Date(item.lastSuccessAt).toLocaleString()}`:"Waiting for first sync"}</p><p className="mt-1 text-xs text-stone-500">{item.latencyMs?`${item.latencyMs} ms`:"No latency recorded"}</p>{item.lastError&&<p className="mt-2 text-xs text-red-700">{item.lastError}</p>}</article>})}<article className="md:col-span-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><strong>Attention</strong><p className="mt-1 text-sm text-stone-700">{services?.attentionCount||0} failed syncs or changes need review · {inbox.filter(item=>item.unread).length} unread important messages.</p></article></div>}
      {tab==="Important Email"&&<div><div className="mb-4 flex items-center gap-2"><Inbox className="h-5 w-5 text-blue-700"/><div><h3 className="font-semibold">Important email only</h3><p className="text-xs text-stone-500">Bodies are fetched temporarily only when you select Analyse.</p></div></div><div className="divide-y rounded-xl border">{inbox.map(mail=><article key={mail.id} className="grid gap-3 p-4 md:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2"><strong className="text-sm">{mail.subject||"No subject"}</strong>{mail.unread&&<span className="rounded bg-blue-100 px-2 py-0.5 text-[10px] font-bold text-blue-800">UNREAD</span>}</div><p className="mt-1 text-xs text-stone-500">{mail.from} · {mail.reasonSelected} · {mail.date}</p>{mail.review?.summary&&<p className="mt-2 text-xs text-stone-700">{mail.review.summary}</p>}</div><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>act(mail.id,`/api/google/inbox/${mail.id}/analyse`)}>Analyse</button>{mail.review&&<button className={button} onClick={()=>act(`task-${mail.id}`,`/api/google/inbox/${mail.id}/proposals`,"POST",{kind:"task"})}>Propose task</button>}</div></article>)}{!inbox.length&&<p className="p-6 text-sm text-stone-500">No important, starred, unread, or approved-rule email is waiting.</p>}</div></div>}
      {tab==="Calendar"&&<div className="grid gap-4 lg:grid-cols-[320px_1fr]"><article className="rounded-xl border p-4"><CalendarDays className="h-5 w-5 text-blue-700"/><h3 className="mt-2 font-semibold">Reconcile LifeOS plan</h3><p className="mt-1 text-xs text-stone-500">Personal events remain read-only. Approval can change only LifeOS-owned events.</p>{["day","shift-cycle","seven-days"].map(range=><button key={range} className={`${button} mt-3 w-full`} onClick={()=>act(range,"/api/google/calendar/reconcile-preview","POST",{startDate:today,range})}>Preview {range.replace("-"," ")}</button>)}</article><article className="rounded-xl border p-4"><h3 className="font-semibold">Upcoming constraints</h3><div className="mt-3 space-y-2">{(status.upcomingEvents||[]).map((event:any)=><a key={event.id} href={event.htmlLink} target="_blank" rel="noreferrer" className="block rounded-lg bg-stone-50 p-3 text-xs"><strong>{event.title}</strong><span className="mt-1 block text-stone-500">{event.start}</span></a>)}</div></article></div>}
      {tab==="Drive Knowledge"&&<div><div className="flex flex-wrap items-end gap-2"><label className="flex-1 text-xs font-semibold">Search approved Drive knowledge<input value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3" placeholder="business plan, customer research, roadmap…"/></label><button className={button} onClick={async()=>{setBusy("search");try{setResults((await api(`/api/google/drive/search?q=${encodeURIComponent(query)}`)).results||[])}finally{setBusy("")}}}><FileSearch className="h-4 w-4"/> Search</button></div><div className="mt-3 flex flex-wrap gap-2"><label className={`${button} cursor-pointer`}>Choose file to upload<input type="file" className="sr-only" accept=".pdf,.md,.txt,.csv,.xlsx,.pptx" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>void act("upload","/api/google/drive/upload-proposal","POST",{name:file.name,mimeType:file.type||"application/octet-stream",dataBase64:String(reader.result||"")});reader.readAsDataURL(file);e.currentTarget.value=""}}/></label><button className={button} onClick={()=>act("folders","/api/google/drive/structure-proposal")}>Prepare managed folders</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{results.map(item=><a key={item.id} href={item.sourceLink} target="_blank" rel="noreferrer" className="rounded-xl border p-4"><strong className="text-sm">{item.name}</strong><p className="mt-2 text-xs text-stone-600">{item.excerpt}</p></a>)}{!results.length&&(workspace?.resources||[]).map((item:any)=><article key={item.id} className="rounded-xl border p-4"><a href={item.link} target="_blank" rel="noreferrer" className="font-semibold text-blue-800">{item.name||"Open Drive resource"}</a><button className={`${button} mt-3 w-full`} onClick={()=>act(item.id,`/api/google/drive/index/${item.id}`)}>Index for AI search</button></article>)}</div><div className="mt-5"><h4 className="text-xs font-bold uppercase text-stone-500">Managed structure</h4><div className="mt-2 flex flex-wrap gap-2">{(workspace?.folders||[]).map((folder:string)=><span key={folder} className="rounded-lg bg-stone-100 px-3 py-2 text-xs"><Cloud className="mr-1 inline h-3.5 w-3.5"/>{folder}</span>)}</div></div></div>}
      {tab==="Proposals"&&<div className="space-y-3">{pending.map((proposal:any)=><article key={proposal.id} className="rounded-xl border border-violet-200 bg-violet-50 p-4"><strong>{proposal.title}</strong><p className="mt-1 text-xs text-stone-600">{proposal.summary}</p><div className="mt-3 flex gap-2"><button className="life-button-primary min-h-11" onClick={()=>act(proposal.id,`/api/google/proposals/${proposal.id}`,"PATCH",{decision:"approve"})}><Check className="h-4 w-4"/> Approve</button><button className={button} onClick={()=>act(proposal.id,`/api/google/proposals/${proposal.id}`,"PATCH",{decision:"reject"})}>Reject</button></div></article>)}{!pending.length&&<p className="rounded-xl border p-6 text-sm text-stone-500">No Google changes await approval.</p>}</div>}
      {tab==="Sync History"&&<div className="space-y-2">{(services?.lastRuns||[]).map((run:any)=><article key={run.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-xs"><span><History className="mr-2 inline h-4 w-4"/><strong>{run.trigger}</strong> · {new Date(run.startedAt).toLocaleString()}</span><span className={run.status==="success"?"text-emerald-700":"text-amber-800"}>{run.status}</span></article>)}</div>}
      {tab==="Privacy"&&<div className="grid gap-3 md:grid-cols-2"><article className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><Shield className="h-5 w-5 text-emerald-700"/><h3 className="mt-2 font-semibold">Protected by default</h3><ul className="mt-2 space-y-2 text-xs text-stone-700"><li>Credentials remain in the encrypted local vault.</li><li>Scheduled sync stores Gmail metadata, not full bodies.</li><li>Drive raw content never becomes permanent AI memory.</li><li>Personal Calendar events are read-only constraints.</li></ul></article><article className="rounded-xl border border-amber-200 bg-amber-50 p-4"><TriangleAlert className="h-5 w-5 text-amber-700"/><h3 className="mt-2 font-semibold">Approval boundary</h3><p className="mt-2 text-xs text-stone-700">External Calendar and Drive writes stay pending until you approve the exact proposal. Gmail send, delete, archive, label, and reply are disabled in this phase.</p></article></div>}
      {(tab==="Tasks"||tab==="Sheets"||tab==="Contacts")&&<GoogleBusinessPanel view={tab} onChanged={refresh}/>}
    </div>
  </section>;
}
