import React,{useEffect,useState} from "react";
import {CheckSquare,Contact,RefreshCw,Search,Sheet} from "lucide-react";
const api=async(url:string,options?:RequestInit)=>{const response=await fetch(url,options),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||"Google request failed.");return result};
const button="life-button-secondary min-h-11";
export default function GoogleBusinessPanel({view,onChanged}:{view:"Tasks"|"Sheets"|"Contacts";onChanged:()=>Promise<void>}){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>setData(await api(view==="Tasks"?"/api/google/tasks":view==="Sheets"?"/api/google/sheets":`/api/google/contacts?q=${encodeURIComponent(query)}`));
 useEffect(()=>{void load().catch(error=>setNotice(error.message))},[view]);
 const act=async(name:string,url:string,body:any={})=>{setBusy(name);setNotice("");try{await api(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice("Prepared successfully. Review it in Proposals before anything is changed.");await load();await onChanged()}catch(error:any){setNotice(error.message)}finally{setBusy("")}};
 if(!data)return <RefreshCw className="h-5 w-5 animate-spin"/>;
 if(view==="Tasks")return <div><Header icon={CheckSquare} title="Google Tasks bridge" detail="LifeOS stays authoritative; Google changes enter as reviewable suggestions."/><div className="mb-3 flex flex-wrap gap-2"><button className={button} disabled={!!busy} onClick={()=>act("sync","/api/google/business/sync")}>Sync Tasks, Sheets and Contacts</button><button className={button} disabled={!!busy} onClick={()=>act("reconcile","/api/google/tasks/reconcile-preview")}>Refresh reconciliation</button></div><Notice value={notice}/><h4 className="mb-2 text-xs font-bold uppercase text-stone-500">LifeOS tasks</h4><div className="mb-5 grid gap-2 md:grid-cols-2">{(data.lifeTasks||[]).map((task:any)=><article key={task.id} className="flex items-center justify-between gap-3 rounded-xl border bg-stone-50 p-3"><div><strong className="text-xs">{task.title}</strong><p className="text-[9px] text-stone-500">{task.dueDate||"No due date"}</p></div><button className={button} onClick={()=>act(task.id,`/api/google/tasks/${task.id}/publish-proposal`)}>{task.published?"Prepare update":"Prepare publish"}</button></article>)}</div><h4 className="mb-2 text-xs font-bold uppercase text-stone-500">Google Tasks suggestions</h4><div className="divide-y rounded-xl border">{(data.records||[]).map((task:any)=><article key={`${task.taskListId}-${task.id}`} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><strong className="text-sm">{task.title}</strong><p className="text-[10px] text-stone-500">{task.taskListTitle} · {task.status} · {task.due?.slice(0,10)||"No due date"}</p></div>{!data.mappings?.some((item:any)=>item.googleTaskId===task.id)&&<button className={button} onClick={()=>act(task.id,`/api/google/tasks/${task.id}/import-proposal`)}>Propose import</button>}</article>)}{!data.records?.length&&<p className="p-6 text-sm text-stone-500">No synchronized Google Tasks yet. Reconnect once with the new permission, then sync.</p>}</div></div>;
 if(view==="Sheets")return <div><Header icon={Sheet} title="Managed business spreadsheets" detail="Reporting copies only. SQLite remains the authoritative source."/><button className={button} disabled={!!busy} onClick={()=>act("workspace","/api/google/sheets/workspace-proposal")}>Prepare six managed spreadsheets</button><Notice value={notice}/><div className="mt-4 grid gap-3 md:grid-cols-2">{(data.records||[]).map((sheet:any)=><article key={sheet.spreadsheetId} className="rounded-xl border p-4"><a href={sheet.webViewLink} target="_blank" rel="noreferrer" className="font-semibold text-blue-800">{sheet.name}</a><p className="mt-1 text-[10px] text-stone-500">Owned range {sheet.ownedRange} · {sheet.lastExportAt?`exported ${new Date(sheet.lastExportAt).toLocaleString()}`:"not exported"}</p><button className={`${button} mt-3 w-full`} onClick={()=>act(sheet.spreadsheetId,`/api/google/sheets/${sheet.spreadsheetId}/export-preview`)}>Preview current export</button></article>)}{!data.records?.length&&<p className="text-sm text-stone-500">No managed spreadsheets have been approved yet.</p>}</div></div>;
 return <div><Header icon={Contact} title="Contacts and lightweight CRM" detail="Only contacts you explicitly link become LifeOS CRM records or AI context."/><div className="mb-4 flex gap-2"><label className="relative flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-stone-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-h-11 w-full rounded-lg border pl-9 pr-3 text-sm" placeholder="Search synchronized contacts"/></label><button className={button} onClick={()=>void load()}>Search</button></div><Notice value={notice}/><div className="divide-y rounded-xl border">{(data.records||[]).map((contact:any)=><article key={contact.resourceName} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><strong className="text-sm">{contact.displayName}</strong><p className="text-[10px] text-stone-500">{contact.organization||contact.email||"No organization or email"}</p></div>{contact.linked?<span className="rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-bold text-emerald-800">Linked to CRM</span>:<button className={button} onClick={()=>act(contact.resourceName,`/api/google/contacts/${encodeURIComponent(contact.resourceName)}/import-proposal`,{relationship:"lead"})}>Propose CRM link</button>}</article>)}</div></div>
}
function Header({icon:Icon,title,detail}:{icon:any;title:string;detail:string}){return <div className="mb-4 flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5"/></span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-stone-500">{detail}</p></div></div>}
function Notice({value}:{value:string}){return value?<p className="my-3 rounded-lg bg-blue-50 p-3 text-xs text-blue-900">{value}</p>:null}
