import React, { useEffect, useState } from "react";
import { BellRing, Brain, Check, ChevronDown, DatabaseBackup, RefreshCw, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import { confirmLifeOs, promptLifeOs } from "../ui/feedback";

const money = new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" });

export default function OperationsCommandCenter({ onActivity }: { onActivity: (message: string) => void }) {
  const [data, setData] = useState<any>(null);
  const [backups, setBackups] = useState<any[]>([]);
  const [memory, setMemory] = useState("");
  const [busy, setBusy] = useState(false);
  const [memoryOpen, setMemoryOpen] = useState(false);
  const [recoveryOpen, setRecoveryOpen] = useState(false);
  const load = async () => {
    const [centerResponse, backupResponse] = await Promise.all([fetch("/api/personal/command-center"), fetch("/api/backups")]);
    if (centerResponse.ok) setData(await centerResponse.json());
    if (backupResponse.ok) setBackups(await backupResponse.json());
  };
  useEffect(() => { void load(); }, []);
  const request = async (url: string, method: string, body?: unknown) => {
    setBusy(true);
    try {
      const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
      const result = response.status === 204 ? null : await response.json();
      if (!response.ok) throw new Error(result?.error || "Action failed");
      await load(); return result;
    } finally { setBusy(false); }
  };
  if (!data) return <div className="bg-white border rounded-2xl p-6 text-sm text-stone-500">Loading your command centre…</div>;
  return <div className="space-y-5">
    <section className="bg-stone-900 text-white rounded-2xl p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-emerald-400"/><h2 className="font-bold">{data.briefing.title}</h2></div><p className="text-sm text-stone-300 mt-2">{data.briefing.summary}</p><p className="mt-4 text-xs uppercase tracking-wide text-emerald-300">Safest next action</p><p className="font-semibold mt-1">{data.briefing.nextAction}</p></div><button disabled={busy} onClick={async () => { const result = await request("/api/ai/actions/refresh", "POST"); onActivity(`AI prepared ${result.created} reviewable action proposals.`); }} className="bg-emerald-500 text-stone-950 rounded-xl px-4 py-2 text-xs font-bold flex items-center gap-2 disabled:opacity-50"><RefreshCw className="h-4 w-4"/>Refresh AI actions</button></div>
    </section>

    <section className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[["Income", data.finance.income], ["Expenses", data.finance.expenses], ["Payments", data.finance.payments], ["Commitments", data.finance.commitments], ["Remaining", data.finance.remaining], ["Safe extra", data.finance.safeExtra]].map(([label, value]) => <div key={String(label)} className="bg-white border rounded-xl p-3"><span className="text-[10px] uppercase text-stone-500">{label}</span><strong className="block mt-1 text-sm">{money.format(Number(value))}</strong></div>)}</section>

    <div className="grid xl:grid-cols-2 gap-5">
      <section className="bg-white border rounded-2xl p-5"><h3 className="font-semibold flex items-center gap-2"><BellRing className="h-4 w-4 text-amber-600"/>Alerts and reminders</h3>{data.alerts.length === 0 ? <p className="text-sm text-emerald-700 mt-3">No active alerts.</p> : <div className="space-y-2 mt-3">{data.alerts.map((alert: any) => <div key={alert.id} className={`border rounded-xl p-3 ${alert.priority === "high" ? "bg-red-50 border-red-200" : "bg-amber-50 border-amber-200"}`}><strong className="text-sm">{alert.title}</strong><p className="text-xs text-stone-600 mt-1">{alert.description}</p></div>)}</div>}</section>
      <section className="bg-white border rounded-2xl p-5"><h3 className="font-semibold flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-700"/>Approval queue</h3><p className="text-xs text-stone-500 mt-1">Review every proposed change. AI cannot apply it without approval.</p>{data.actions.length === 0 ? <p className="text-sm text-stone-500 mt-4">No pending actions. Select Refresh AI actions to scan due payments and imported transactions.</p> : <div className="space-y-3 mt-3">{data.actions.map((action: any) => <div key={action.id} className="border rounded-xl p-3"><strong className="text-sm">{action.title}</strong><p className="text-xs text-stone-600 mt-1">{action.explanation}</p><div className="flex gap-2 mt-3"><button disabled={busy} onClick={async () => { let payload = action.payload; if (action.type === "record_payment") { const value = await promptLifeOs("Confirm or change payment amount", String(action.payload.amount)); if (!value) return; payload = { ...payload, amount: Number(value) }; } if (action.type === "reconcile_transaction") { const value = await promptLifeOs("Confirm or change category", String(action.payload.category)); if (!value) return; payload = { ...payload, category: value }; } await request(`/api/ai/actions/${action.id}`, "PATCH", { decision: "approve", payload }); onActivity(`Approved AI proposal: ${action.title}`); }} className="bg-emerald-700 text-white rounded-lg px-3 py-1.5 text-xs flex gap-1"><Check className="h-3.5 w-3.5"/>Approve</button><button disabled={busy} onClick={async () => { await request(`/api/ai/actions/${action.id}`, "PATCH", { decision: "reject" }); onActivity(`Rejected AI proposal: ${action.title}`); }} className="border border-red-200 text-red-700 rounded-lg px-3 py-1.5 text-xs flex gap-1"><X className="h-3.5 w-3.5"/>Reject</button></div></div>)}</div>}</section>
    </div>

    <div className="grid xl:grid-cols-2 gap-4 items-start">
      <section className="bg-white border rounded-2xl overflow-hidden shadow-sm"><button type="button" onClick={()=>setMemoryOpen(value=>!value)} className="w-full p-4 flex items-center justify-between gap-3 text-left hover:bg-purple-50/50"><div className="flex items-center gap-3 min-w-0"><span className="h-9 w-9 rounded-xl bg-purple-100 text-purple-700 flex items-center justify-center shrink-0"><Brain className="h-4 w-4"/></span><div className="min-w-0"><h3 className="font-semibold text-sm">What LifeOS remembers</h3><p className="text-xs text-stone-500 truncate">{data.memories.length} saved memories used by your AI</p></div></div><ChevronDown className={`h-4 w-4 text-stone-400 transition ${memoryOpen?"rotate-180":""}`}/></button>{memoryOpen&&<div className="border-t p-4"><form onSubmit={async(event)=>{event.preventDefault();if(!memory.trim())return;await request("/api/ai/memories","POST",{content:memory,category:"preference"});setMemory("");onActivity("Confirmed AI memory saved.");}} className="flex gap-2"><input value={memory} onChange={event=>setMemory(event.target.value)} placeholder="Add a fact or preference" className="border rounded-lg px-3 py-2 flex-1 min-w-0 text-sm"/><button disabled={busy} className="bg-purple-700 text-white rounded-lg px-3 text-xs">Remember</button></form><div className="mt-3 max-h-72 overflow-y-auto space-y-2 pr-1">{data.memories.map((item:any)=><div key={item.id} className="border rounded-xl p-3 flex justify-between gap-3"><div className="min-w-0"><p className="text-xs leading-5 line-clamp-3">{item.content}</p><span className="text-[9px] uppercase text-stone-400">{item.category}</span></div><div className="flex gap-1 shrink-0"><button onClick={async()=>{const value=await promptLifeOs("Edit memory",item.content);if(value?.trim())await request(`/api/ai/memories/${item.id}`,"PATCH",{content:value,category:item.category});}} className="text-[10px] border rounded px-2 h-7">Edit</button><button onClick={()=>request(`/api/ai/memories/${item.id}`,"DELETE")} className="text-red-700 h-7 w-7 flex items-center justify-center"><Trash2 className="h-3.5 w-3.5"/></button></div></div>)}</div></div>}</section>
      <section className="bg-white border rounded-2xl overflow-hidden shadow-sm"><button type="button" onClick={()=>setRecoveryOpen(value=>!value)} className="w-full p-4 flex items-center justify-between gap-3 text-left hover:bg-blue-50/50"><div className="flex items-center gap-3 min-w-0"><span className="h-9 w-9 rounded-xl bg-blue-100 text-blue-700 flex items-center justify-center shrink-0"><DatabaseBackup className="h-4 w-4"/></span><div className="min-w-0"><h3 className="font-semibold text-sm">Recovery and audit</h3><p className="text-xs text-stone-500 truncate">{backups.length} backups · {data.audit.length} recent audit events</p></div></div><ChevronDown className={`h-4 w-4 text-stone-400 transition ${recoveryOpen?"rotate-180":""}`}/></button>{recoveryOpen&&<div className="border-t p-4"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={async()=>{const result=await request("/api/backups","POST");onActivity(`Backup created: ${result.filename}`);}} className="bg-blue-700 text-white rounded-lg px-3 py-2 text-xs">Create backup</button><a href="/api/workbook/snapshot" target="_blank" rel="noreferrer" className="border rounded-lg px-3 py-2 text-xs text-blue-700">Export data</a></div><div className="grid md:grid-cols-2 gap-3 mt-4"><div><h4 className="text-[10px] uppercase font-bold text-stone-500 mb-2">Latest backups</h4><div className="max-h-56 overflow-y-auto space-y-2 pr-1">{backups.slice(0,8).map(backup=><div key={backup.filename} className="border rounded-lg p-2 flex justify-between gap-2 items-center"><div className="min-w-0"><p className="text-[11px] truncate">{backup.filename}</p><span className="text-[9px] text-stone-400">{new Date(backup.createdAt).toLocaleString("en-ZA")}</span></div><button disabled={busy} onClick={async()=>{if(!await confirmLifeOs(`Restore ${backup.filename}? A fresh backup should be created first.`))return;await request(`/api/backups/${encodeURIComponent(backup.filename)}/restore`,"POST");onActivity(`Restored backup: ${backup.filename}`);}} className="text-[10px] border border-amber-300 text-amber-800 rounded px-2 py-1 shrink-0">Restore</button></div>)}</div></div><div><h4 className="text-[10px] uppercase font-bold text-stone-500 mb-2">Recent audit</h4><div className="max-h-56 overflow-y-auto space-y-2 pr-1">{data.audit.map((item:any)=><div key={item.id} className="border-l-2 border-stone-200 pl-2"><p className="text-[11px] text-stone-700 leading-4">{item.action.replaceAll("_"," ")}</p><span className="text-[9px] text-stone-400">{new Date(item.createdAt).toLocaleString("en-ZA")}</span></div>)}</div></div></div></div>}</section>
    </div>
  </div>;
}
