import React, { useEffect, useMemo, useState } from "react";
import { BarChart3, Briefcase, CalendarDays, Clock3, Flame, Plus, RefreshCw, Sparkles, Trash2 } from "lucide-react";
import MarkdownMessage from "./MarkdownMessage";
import { promptLifeOs } from "../ui/feedback";

type View = "projects" | "calendar" | "habits" | "focus" | "reviews" | "analytics";
const today = () => new Date().toISOString().slice(0, 10);
const field = "w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm";
const button = "rounded-lg bg-stone-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-40";

export default function PlannerSecondaryWorkspace({ initialView, onActivity }: { initialView: View; onActivity: (message: string) => void }) {
  const [data, setData] = useState<any>({ projects: [], tasks: [], goals: [], habits: [], focus: [], analytics: {}, reviews: [] });
  const [busy, setBusy] = useState(false);
  const [project, setProject] = useState({ title: "", priority: "Medium", timeline: "", objectives: "" });
  const [habit, setHabit] = useState({ name: "", category: "Personal", frequency: "Daily", target: "Daily" });
  const [session, setSession] = useState({ title: "", category: "Work", taskId: "" });
  const [reviewType, setReviewType] = useState("weekly");
  const load = async () => {
    const paths = ["projects", "tasks", "goals", "habits", "focus", "planning/analytics", "planning/reviews"];
    const values = await Promise.all(paths.map(path => fetch(`/api/${path}`).then(r => r.ok ? r.json() : path.includes("analytics") ? {} : [])));
    setData({ projects: values[0], tasks: values[1], goals: values[2], habits: values[3], focus: values[4], analytics: values[5], reviews: values[6] });
  };
  useEffect(() => { load(); }, []);
  const run = async (path: string, options: RequestInit, message: string) => { setBusy(true); try { const response = await fetch(path, options); const result = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(result?.error || "Update failed"); onActivity(message); await load(); return result; } catch (error: any) { alert(error.message); } finally { setBusy(false); } };
  const post = (path: string, body: any, message: string) => run(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }, message);
  const scheduled = useMemo(() => [...data.tasks].sort((a: any, b: any) => String(a.dueDate || "9999").localeCompare(String(b.dueDate || "9999"))), [data.tasks]);
  const active = data.focus.find((item: any) => item.active);
  const icons: any = { projects: Briefcase, calendar: CalendarDays, habits: Flame, focus: Clock3, reviews: Sparkles, analytics: BarChart3 };
  const Icon = icons[initialView];
  const title: any = { projects: "Projects", calendar: "Schedule", habits: "Habits", focus: "Focus", reviews: "Reviews", analytics: "Progress" };
  return <div className="space-y-4">
    <header className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Icon className="h-5 w-5 text-emerald-600"/><div><h2 className="font-bold text-stone-900">{title[initialView]}</h2><p className="text-xs text-stone-500">Saved records only · changes persist automatically</p></div></div><button onClick={load} className="rounded-lg border border-stone-200 p-2"><RefreshCw className="h-4 w-4"/></button></header>

    {initialView === "projects" && <><form className="grid gap-2 rounded-xl bg-stone-50 p-3 md:grid-cols-5" onSubmit={async e => { e.preventDefault(); if (!project.title) return; await post("/api/projects", project, `Created project: ${project.title}`); setProject({ title: "", priority: "Medium", timeline: "", objectives: "" }); }}><input className={field} placeholder="Project name" value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/><select className={field} value={project.priority} onChange={e=>setProject({...project,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select><input className={field} type="date" value={project.timeline} onChange={e=>setProject({...project,timeline:e.target.value})}/><input className={field} placeholder="Objective" value={project.objectives} onChange={e=>setProject({...project,objectives:e.target.value})}/><button className={button} disabled={busy}><Plus className="mr-1 inline h-3 w-3"/>Add</button></form><div className="grid gap-2 md:grid-cols-2">{data.projects.map((p:any)=><article key={p.id} className="rounded-xl border border-stone-200 p-3"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{p.title}</strong><p className="mt-1 text-xs text-stone-500">{p.objectives || "No objective yet"}</p></div><button title="Delete project" onClick={()=>post("/api/projects/delete",{id:p.id},`Deleted project: ${p.title}`)} className="text-stone-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 flex gap-2"><select className={field} value={p.status || "Planning"} onChange={e=>run(`/api/projects/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:e.target.value})},`Updated project: ${p.title}`)}><option>Planning</option><option>Active</option><option>On Hold</option><option>Completed</option></select><select className={field} value={p.priority || "Medium"} onChange={e=>run(`/api/projects/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({priority:e.target.value})},`Updated project: ${p.title}`)}><option>High</option><option>Medium</option><option>Low</option></select></div></article>)}</div></>}

    {initialView === "calendar" && <div className="space-y-2">{scheduled.map((task:any)=>{const overdue=task.status!=="completed"&&task.dueDate&&task.dueDate<today();return <article key={task.id} className="grid items-center gap-2 rounded-xl border border-stone-200 p-3 md:grid-cols-[1fr_160px_120px]"><div><strong className="text-sm">{task.title}</strong><p className="text-xs text-stone-500">{data.projects.find((p:any)=>p.id===task.projectId)?.title || "Independent task"}{overdue?" · Overdue":""}</p></div><input className={field} type="date" value={task.dueDate||""} onChange={e=>run(`/api/tasks/${task.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({dueDate:e.target.value})},`Rescheduled: ${task.title}`)}/><span className={`rounded-full px-2 py-1 text-center text-[10px] font-bold ${task.status==="completed"?"bg-emerald-100 text-emerald-700":overdue?"bg-red-100 text-red-700":"bg-stone-100"}`}>{task.status||"pending"}</span></article>})}{!scheduled.length&&<Empty text="No tasks scheduled yet."/>}</div>}

    {initialView === "habits" && <><form className="grid gap-2 rounded-xl bg-stone-50 p-3 md:grid-cols-5" onSubmit={async e=>{e.preventDefault();if(!habit.name)return;await post("/api/habits",habit,`Created habit: ${habit.name}`);setHabit({name:"",category:"Personal",frequency:"Daily",target:"Daily"});}}><input className={field} placeholder="Habit name" value={habit.name} onChange={e=>setHabit({...habit,name:e.target.value})}/><input className={field} placeholder="Category" value={habit.category} onChange={e=>setHabit({...habit,category:e.target.value})}/><select className={field} value={habit.frequency} onChange={e=>setHabit({...habit,frequency:e.target.value})}><option>Daily</option><option>Weekly</option><option>Weekdays</option></select><input className={field} placeholder="Target" value={habit.target} onChange={e=>setHabit({...habit,target:e.target.value})}/><button className={button}><Plus className="mr-1 inline h-3 w-3"/>Add</button></form><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{data.habits.map((h:any)=>{const done=(h.logs||[]).includes(today());return <article key={h.id} className="rounded-xl border border-stone-200 p-3"><div className="flex justify-between"><div><strong className="text-sm">{h.name}</strong><p className="text-xs text-stone-500">{h.category} · {(h.logs||[]).length} logged</p></div><button onClick={()=>run(`/api/habits/${h.id}`,{method:"DELETE"},`Deleted habit: ${h.name}`)}><Trash2 className="h-4 w-4 text-stone-400"/></button></div><button disabled={done||busy} onClick={()=>post("/api/habits/log",{id:h.id},`Logged habit: ${h.name}`)} className={`${button} mt-3 w-full ${done?"!bg-emerald-600":""}`}>{done?"Completed today":"Log today"}</button></article>})}</div></>}

    {initialView === "focus" && <>{active?<div className="rounded-xl bg-stone-900 p-5 text-white"><p className="text-xs text-emerald-400">ACTIVE SESSION</p><h3 className="mt-1 font-bold">{active.title}</h3><p className="text-xs text-stone-400">Started {new Date(active.startedAt||active.timestamp).toLocaleString()}</p><button className="mt-4 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-stone-950" onClick={async()=>{const duration=await promptLifeOs("Actual focused minutes?");if(duration)post("/api/focus/end",{id:active.id,duration:Number(duration),interrupts:Number(await promptLifeOs("Interruptions?","0")||0),flowScore:Number(await promptLifeOs("Optional focus score 0–100","")||NaN)},`Completed focus session: `)}}>End and record</button></div>:<form className="grid gap-2 rounded-xl bg-stone-50 p-3 md:grid-cols-4" onSubmit={async e=>{e.preventDefault();if(!session.title)return;await post("/api/focus/start",session,`Started focus session: ${session.title}`);setSession({...session,title:""});}}><input className={field} placeholder="Focus outcome" value={session.title} onChange={e=>setSession({...session,title:e.target.value})}/><input className={field} placeholder="Category" value={session.category} onChange={e=>setSession({...session,category:e.target.value})}/><select className={field} value={session.taskId} onChange={e=>setSession({...session,taskId:e.target.value})}><option value="">No linked task</option>{data.tasks.filter((t:any)=>t.status!=="completed").map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button className={button}>Start focus</button></form>}<div className="grid gap-2 md:grid-cols-3">{data.focus.filter((f:any)=>!f.active).slice(0,9).map((f:any)=><article key={f.id} className="rounded-xl border border-stone-200 p-3"><strong className="text-sm">{f.title}</strong><p className="mt-1 text-xs text-stone-500">{f.duration} min · {f.interrupts||0} interruptions{f.flowScore!=null?` · ${f.flowScore}/100`:""}</p></article>)}</div></>}

    {initialView === "reviews" && <><div className="flex gap-2 rounded-xl bg-stone-50 p-3"><select className={field} value={reviewType} onChange={e=>setReviewType(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><button disabled={busy} className={button} onClick={()=>post("/api/planning/ai-review",{type:reviewType},`Created ${reviewType} review`)}>Generate from records</button></div><div className="space-y-3">{data.reviews.map((r:any)=><article key={r.id} className="rounded-xl border border-stone-200 p-4"><div className="mb-3 flex justify-between text-[10px] uppercase text-stone-500"><span>{r.type} · {r.provider}</span><span>{new Date(r.createdAt).toLocaleString()}</span></div><MarkdownMessage content={r.content}/></article>)}{!data.reviews.length&&<Empty text="No saved reviews yet."/>}</div></>}

    {initialView === "analytics" && <><div className="grid grid-cols-2 gap-2 md:grid-cols-5"><Metric label="Tasks complete" value={`${data.analytics.completedTasks||0}/${data.analytics.totalTasks||0}`}/><Metric label="Completion" value={`${data.analytics.completionRate||0}%`}/><Metric label="Focus" value={`${data.analytics.totalFocusMinutes||0}m`}/><Metric label="Habit consistency" value={data.analytics.habitConsistency==null?"No data":`${data.analytics.habitConsistency}%`}/><Metric label="Avg focus score" value={data.analytics.avgFlowScore==null?"No data":data.analytics.avgFlowScore}/></div><div className="overflow-x-auto rounded-xl border border-stone-200"><table className="w-full text-left text-xs"><thead className="bg-stone-50 text-stone-500"><tr><th className="p-3">Day</th><th>Focus</th><th>Tasks</th><th>Habits</th></tr></thead><tbody>{(data.analytics.productivityTrends||[]).map((d:any)=><tr key={d.date} className="border-t border-stone-100"><td className="p-3 font-bold">{d.day} <span className="font-normal text-stone-400">{d.date}</span></td><td>{d.focusMinutes}m</td><td>{d.tasksCompleted}</td><td>{d.habitsCompleted}</td></tr>)}</tbody></table></div></>}
  </div>;
}

function Metric({label,value}:{label:string,value:any}) { return <div className="rounded-xl border border-stone-200 p-3"><p className="text-[10px] uppercase text-stone-500">{label}</p><strong className="mt-1 block text-xl">{value}</strong></div> }
function Empty({text}:{text:string}) { return <div className="rounded-xl border border-dashed border-stone-300 p-8 text-center text-sm text-stone-500">{text}</div> }
