import React,{useEffect,useState} from "react";
import { Banknote, CreditCard, Plus, RefreshCw, WalletCards } from "lucide-react";
const money=new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}),field="rounded-lg border border-stone-200 px-3 py-2 text-sm";
export default function QuickMoneyPanel({onSaved,onActivity}:{onSaved:()=>Promise<void>|void;onActivity:(message:string)=>void}){
 const [data,setData]=useState<any>({accounts:[],cards:[]}),[busy,setBusy]=useState(false),[spend,setSpend]=useState({date:new Date().toISOString().slice(0,10),amount:"",category:"Food & daily spending",description:""}),[balances,setBalances]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch("/api/personal/overview");if(!r.ok)return;const x=await r.json(),accounts=x.finance.bankAccounts||[],cards=(x.finance.debts||[]).filter((d:any)=>d.liabilityType==="Credit card"&&d.status!=="Paid");setData({accounts,cards});setBalances(Object.fromEntries([...accounts,...cards].map((a:any)=>[a.id,String(a.balance)])))};
 useEffect(()=>{load()},[]);
 const saveSpend=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch("/api/personal/finance/entries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...spend,type:"expense",amount:Number(spend.amount)})});const result=await r.json();if(!r.ok)throw new Error(result.error);setSpend({...spend,amount:"",description:""});onActivity("Daily spending recorded.");await load();await onSaved()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 const saveBalances=async()=>{setBusy(true);try{for(const account of data.accounts){const value=Number(balances[account.id]);if(Number.isFinite(value)&&value!==Number(account.balance)){const r=await fetch(`/api/personal/finance/bank-accounts/${account.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({balance:value,balanceAsOf:new Date().toISOString().slice(0,10)})});if(!r.ok)throw new Error((await r.json()).error)}}for(const card of data.cards){const value=Number(balances[card.id]);if(Number.isFinite(value)&&value!==Number(card.balance)){const r=await fetch(`/api/personal/finance/debts/${card.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({balance:value})});if(!r.ok)throw new Error((await r.json()).error)}}onActivity("Current bank and credit balances updated.");await load();await onSaved()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 return <details className="rounded-2xl border bg-white"><summary className="flex cursor-pointer list-none items-center justify-between p-4"><span><strong className="flex items-center gap-2 text-sm"><WalletCards className="h-4 w-4 text-emerald-700"/>Quick money update</strong><small className="mt-1 block text-stone-500">Record today’s spending or refresh every current balance.</small></span><Plus className="h-4 w-4 text-stone-400"/></summary><div className="grid gap-4 border-t p-4 lg:grid-cols-2"><form onSubmit={saveSpend} className="space-y-2"><h3 className="flex items-center gap-2 text-xs font-bold"><Banknote className="h-4 w-4"/>Record daily spending</h3><div className="grid grid-cols-2 gap-2"><input required type="date" className={field} value={spend.date} onChange={e=>setSpend({...spend,date:e.target.value})}/><input required min="0.01" step="0.01" type="number" className={field} placeholder="Amount (R)" value={spend.amount} onChange={e=>setSpend({...spend,amount:e.target.value})}/><select className={field} value={spend.category} onChange={e=>setSpend({...spend,category:e.target.value})}>{["Food & daily spending","Transport","Groceries","Airtime","Cigarettes","Entertainment","Household","Medical","Other"].map(x=><option key={x}>{x}</option>)}</select><input className={field} placeholder="What was it for?" value={spend.description} onChange={e=>setSpend({...spend,description:e.target.value})}/></div><button disabled={busy} className="rounded-lg bg-stone-900 px-4 py-2 text-xs font-bold text-white">Save spending</button></form><div><h3 className="flex items-center gap-2 text-xs font-bold"><CreditCard className="h-4 w-4"/>Current balances</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{data.accounts.map((a:any)=><label key={a.id} className="text-[10px] font-bold text-stone-500">{a.name} · bank balance<input type="number" step="0.01" className={`${field} mt-1 w-full text-stone-900`} value={balances[a.id]??""} onChange={e=>setBalances({...balances,[a.id]:e.target.value})}/></label>)}{data.cards.map((a:any)=><label key={a.id} className="text-[10px] font-bold text-stone-500">{a.name} · amount owed<input type="number" min="0" max={a.creditLimit||undefined} step="0.01" className={`${field} mt-1 w-full text-stone-900`} value={balances[a.id]??""} onChange={e=>setBalances({...balances,[a.id]:e.target.value})}/><span className="mt-1 block font-normal">Limit {money.format(a.creditLimit||0)} · available {money.format(Math.max(0,(a.creditLimit||0)-Number(balances[a.id]||0)))}</span></label>)}</div><button disabled={busy} onClick={saveBalances} className="mt-3 flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 text-xs font-bold text-white"><RefreshCw className="h-3.5 w-3.5"/>Update balances</button></div></div></details>
}
