import React, { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, HardDrive, Moon, RefreshCw, ShieldCheck } from "lucide-react";
import { UserProfile } from "../types";

interface Props { userProfile: UserProfile; onChangeProfile: (profile: UserProfile) => void; onAddSignalREvent: (message: string) => void; theme: "light" | "dark" | "high-contrast"; onChangeTheme: (theme: "light" | "dark" | "high-contrast") => void }
const size = (bytes = 0) => bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export default function SettingsView({ userProfile, onChangeProfile, onAddSignalREvent, theme, onChangeTheme }: Props) {
  const [integrity, setIntegrity] = useState<any>(null), [audit, setAudit] = useState<any[]>([]), [sessions, setSessions] = useState<any[]>([]), [busy, setBusy] = useState(false);
  const load = async () => { const [health, history, sessionList, preferences] = await Promise.all([fetch("/api/system/integrity"), fetch("/api/system/audit?limit=30"), fetch("/api/auth/sessions"), fetch("/api/preferences")]); if ([200,409].includes(health.status)) setIntegrity(await health.json()); if (history.ok) setAudit((await history.json()).events || []); if (sessionList.ok) setSessions(await sessionList.json()); if(preferences.ok){const saved=await preferences.json();if(saved.theme)onChangeTheme(saved.theme);if(saved.privacy||saved.notifications)onChangeProfile({...userProfile,privacy:{...userProfile.privacy,...saved.privacy},notifications:{...userProfile.notifications,...saved.notifications}});} };
  useEffect(() => { void load(); }, []);
  const verify = async () => { setBusy(true); try { const response = await fetch("/api/system/storage-verify", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result?.error?.message || "Verification failed"); await load(); onAddSignalREvent("SQLite storage and normalized domain totals verified."); } catch (error: any) { alert(error.message); } finally { setBusy(false); } };
  const savePreferences=async(body:any)=>{const response=await fetch("/api/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)onAddSignalREvent("Preference could not be saved to this device group.");};
  const toggle = (group: "privacy" | "notifications", key: string) => { const next = { ...userProfile, [group]: { ...(userProfile as any)[group], [key]: !(userProfile as any)[group][key] } }; onChangeProfile(next);void savePreferences({[group]:(next as any)[group]}); };
  const selectTheme=(value:"light"|"dark"|"high-contrast")=>{onChangeTheme(value);void savePreferences({theme:value});};
  return <div className="max-w-6xl mx-auto space-y-5">
    <section className="bg-stone-900 text-white rounded-2xl p-5 flex flex-wrap justify-between gap-4"><div><h2 className="font-bold flex gap-2 items-center"><ShieldCheck className="h-5 w-5 text-emerald-400"/>System integrity</h2><p className="text-sm text-stone-300 mt-2">Real local storage, upload, recovery, and session status. No simulated telemetry.</p></div><button disabled={busy} onClick={() => void verify()} className="bg-emerald-400 text-stone-950 rounded-xl px-4 py-2 text-xs font-bold flex gap-2 items-center disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/>Verify now</button></section>
    {!integrity ? <div className="bg-white border rounded-2xl p-6 text-sm text-stone-500">Loading system integrity…</div> : <>
      <section className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[
        ["SQLite", integrity.sqlite.ok ? "Verified" : "Attention", Database],
        ["Database", size(integrity.storage.databaseSize), HardDrive],
        ["Uploads", `${integrity.uploads.valid}/${integrity.uploads.total} valid`, CheckCircle2],
        ["Last backup", integrity.backup.lastSuccessful ? new Date(integrity.backup.lastSuccessful.createdAt).toLocaleDateString("en-ZA") : "None", ShieldCheck],
        ["Failed operations", String(integrity.audit.failedOperations), AlertTriangle]
      ].map(([label,value,Icon]:any)=><div key={label} className="bg-white border rounded-xl p-3"><Icon className={`h-4 w-4 ${label==="Failed operations"&&Number(value)>0?"text-amber-600":"text-emerald-700"}`}/><span className="block text-[10px] uppercase text-stone-500 mt-2">{label}</span><strong className="text-sm">{value}</strong></div>)}</section>
      {!integrity.ok && <section className="border border-amber-200 bg-amber-50 rounded-xl p-4 text-sm text-amber-900">Integrity needs attention: {integrity.uploads.missing} missing uploads and {integrity.uploads.checksumFailures} checksum failures. SQLite result: {integrity.sqlite.results.join(", ")}.</section>}
    </>}
    <div className="grid lg:grid-cols-2 gap-5">
      <section className="bg-white border rounded-2xl p-5"><h3 className="font-semibold">Appearance and trusted-device preferences</h3><div className="grid grid-cols-3 gap-2 mt-4">{(["light","dark","high-contrast"] as const).map(value=><button key={value} onClick={()=>selectTheme(value)} className={`border rounded-lg p-3 text-xs capitalize ${theme===value?"bg-stone-900 text-white":""}`}><Moon className="h-4 w-4 mx-auto mb-1"/>{value.replace("-"," ")}</button>)}</div><div className="mt-5 space-y-3 text-xs">{Object.entries(userProfile.privacy).map(([key,value])=><label key={key} className="flex justify-between gap-3"><span>{key.replace(/([A-Z])/g," $1")}</span><input type="checkbox" checked={Boolean(value)} onChange={()=>toggle("privacy",key)}/></label>)}</div></section>
      <section className="bg-white border rounded-2xl p-5"><h3 className="font-semibold">Authenticated devices · {sessions.length}</h3><div className="space-y-2 mt-3 max-h-52 overflow-y-auto">{sessions.map(session=><div key={session.id} className="border rounded-lg p-3"><strong className="text-xs">{session.device}</strong><p className="text-[10px] text-stone-500">{session.ipAddress} · {session.isCurrent?"Current session":new Date(session.lastActive).toLocaleString("en-ZA")}</p></div>)}</div><h3 className="font-semibold mt-5">Recent operational audit</h3><div className="space-y-2 mt-3 max-h-64 overflow-y-auto">{audit.map(item=><div key={item.id} className="border-l-2 pl-2"><p className="text-xs capitalize">{String(item.action).replaceAll("_"," ")}</p><span className="text-[9px] text-stone-400">{new Date(item.createdAt || item.timestamp).toLocaleString("en-ZA")}</span></div>)}</div></section>
    </div>
    <details className="bg-white border rounded-2xl p-4"><summary className="text-sm font-semibold cursor-pointer">Notification preferences</summary><div className="grid sm:grid-cols-2 gap-3 mt-3 text-xs">{Object.entries(userProfile.notifications).map(([key,value])=><label key={key} className="flex justify-between gap-3 border rounded-lg p-3"><span>{key.replace(/([A-Z])/g," $1")}</span><input type="checkbox" checked={Boolean(value)} onChange={()=>toggle("notifications",key)}/></label>)}</div></details>
  </div>;
}
