import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Edit3, Focus, Layers, Target } from "lucide-react";

export default function UnifiedLifeVision({ goals, tasks, onNavigate, onActivity }: { goals:any[]; tasks:any[]; onNavigate:(tab:string)=>void; onActivity:(message:string)=>void }) {
  const [vision,setVision]=useState<any>(null),[editing,setEditing]=useState(false),[draft,setDraft]=useState<any>(null),[saving,setSaving]=useState(false);
  const load=async()=>{const response=await fetch("/api/personal/vision");if(response.ok){const data=await response.json();setVision(data);setDraft({...data,principlesText:data.principles.join("\n")});}};
  useEffect(()=>{void load();},[]);
  const activeGoals=goals.filter(goal=>goal.status!=="Archived"&&goal.status!=="Completed");
  const grouped=useMemo(()=>Object.entries(activeGoals.reduce((map:Record<string,any[]>,goal)=>{(map[goal.type||"Other"]??=[]).push(goal);return map;},{})),[goals]);
  const linked=tasks.filter(task=>task.goalId&&goals.some(goal=>goal.id===task.goalId)); const completed=linked.filter(task=>task.status==="completed").length;
  const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await fetch("/api/personal/vision",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({vision:draft.vision,currentFocus:draft.currentFocus,principles:draft.principlesText.split("\n").map((x:string)=>x.trim()).filter(Boolean)})});const result=await response.json();if(!response.ok)return alert(result.error);setEditing(false);onActivity("Unified life vision updated and connected to AI context.");await load();}finally{setSaving(false);}};
  if(!vision)return <div className="bg-white border rounded-2xl p-5 text-sm">Loading your saved life vision…</div>;
  return <div className="space-y-4">
    <section className="bg-stone-900 text-white rounded-2xl p-5"><div className="flex items-start justify-between gap-4"><div><span className="text-[10px] uppercase tracking-wide text-emerald-400 font-bold">North star</span><h2 className="text-lg font-semibold mt-1 max-w-4xl leading-7">{vision.vision}</h2><p className="text-sm text-stone-300 mt-3"><strong className="text-white">Current focus:</strong> {vision.currentFocus}</p></div><button onClick={()=>setEditing(true)} className="border border-stone-700 rounded-lg p-2 shrink-0" title="Edit vision"><Edit3 className="h-4 w-4"/></button></div><div className="flex flex-wrap gap-2 mt-4">{vision.principles.map((item:string)=><span key={item} className="bg-stone-800 border border-stone-700 rounded-full px-3 py-1 text-[10px]">{item}</span>)}</div>{vision.updatedAt&&<p className="text-[9px] text-stone-500 mt-3">Last updated {new Date(vision.updatedAt).toLocaleString("en-ZA")}</p>}</section>
    <div className="grid grid-cols-3 gap-2">{[["Strategic areas",grouped.length],["Active goals",activeGoals.length],["Linked execution",`${completed}/${linked.length}`]].map(([label,value])=><div key={String(label)} className="bg-white border rounded-xl p-3"><span className="block text-[10px] uppercase text-stone-500">{label}</span><strong className="block text-lg mt-1">{value}</strong></div>)}</div>
    <section className="bg-white border rounded-2xl p-4"><div className="flex justify-between"><div><h3 className="font-semibold flex gap-2"><Layers className="h-4 w-4 text-purple-700"/>Vision to execution</h3><p className="text-xs text-stone-500 mt-1">Each level below is generated from your saved goals and tasks.</p></div><button onClick={()=>onNavigate("goals")} className="text-xs text-purple-700">Manage goals</button></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{grouped.map(([type,typeGoals]:any)=><div key={type} className="border rounded-xl p-3"><div className="flex justify-between"><strong className="text-sm">{type}</strong><span className="text-[10px] bg-stone-100 rounded px-2 py-0.5">{typeGoals.length} goal{typeGoals.length===1?"":"s"}</span></div><div className="space-y-2 mt-3">{typeGoals.map((goal:any)=>{const goalTasks=tasks.filter(task=>task.goalId===goal.id);const done=goalTasks.filter(task=>task.status==="completed").length;const progress=goalTasks.length?Math.round(done/goalTasks.length*100):0;return <button key={goal.id} onClick={()=>onNavigate("goals")} className="w-full text-left bg-stone-50 rounded-lg p-2"><div className="flex justify-between gap-2 text-xs"><span className="font-medium truncate">{goal.title}</span><span>{progress}%</span></div><div className="h-1.5 bg-stone-200 rounded mt-1.5"><div className="h-full bg-purple-600 rounded" style={{width:`${progress}%`}}/></div><span className="block text-[9px] text-stone-500 mt-1">{done}/{goalTasks.length} linked tasks · {goal.targetDate||"No deadline"}</span></button>})}</div></div>)}</div></section>
    <section className="grid md:grid-cols-2 gap-3"><div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4"><h3 className="font-semibold text-sm flex gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-700"/>Alignment rules</h3><ul className="text-xs text-emerald-900 mt-2 space-y-1"><li>• Every task should link to a real goal.</li><li>• Goal progress comes from completed linked tasks.</li><li>• Goals need a deadline, KPI and measurable outcome.</li></ul></div><button onClick={()=>onNavigate("tasks")} className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-left"><h3 className="font-semibold text-sm flex gap-2"><Focus className="h-4 w-4 text-blue-700"/>Execution layer</h3><p className="text-xs text-blue-900 mt-2">{tasks.filter(task=>task.status!=="completed").length} open tasks · {tasks.filter(task=>!task.goalId).length} unlinked tasks. Open the task tracker to organize execution.</p></button></section>
    {editing&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setEditing(false);}}><form onSubmit={save} className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl p-5 space-y-3"><div className="flex justify-between"><div><h3 className="font-semibold">Edit unified life vision</h3><p className="text-xs text-stone-500 mt-1">This becomes authoritative context for LifeOS AI.</p></div><button type="button" onClick={()=>setEditing(false)}>×</button></div><label className="block text-xs font-bold">Life vision<textarea required minLength={20} rows={4} value={draft.vision} onChange={e=>setDraft({...draft,vision:e.target.value})} className="block border rounded-lg p-3 w-full mt-1 font-normal"/></label><label className="block text-xs font-bold">Current focus<input required value={draft.currentFocus} onChange={e=>setDraft({...draft,currentFocus:e.target.value})} className="block border rounded-lg p-3 w-full mt-1 font-normal"/></label><label className="block text-xs font-bold">Principles, one per line<textarea required rows={5} value={draft.principlesText} onChange={e=>setDraft({...draft,principlesText:e.target.value})} className="block border rounded-lg p-3 w-full mt-1 font-normal"/></label><button disabled={saving} className="bg-stone-900 text-white rounded-lg px-4 py-2 text-xs font-bold disabled:opacity-50">{saving?"Saving…":"Save vision"}</button></form></div>}
  </div>;
}
