import React,{useEffect,useMemo,useState} from "react";
import { AlertTriangle, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, Plus, RefreshCw, Sparkles, Trash2 } from "lucide-react";
import CodebaseBusinessView from "./CodebaseBusinessView";
import CareerView from "./CareerView";
import { PageHeader, SegmentedTabs } from "../ui/primitives";
import { readSection, updateSection } from "../ui/navigation";
import { confirmLifeOs } from "../ui/feedback";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()), input="w-full rounded-lg border border-stone-200 px-3 py-2 text-sm";
export default function WorkView({onActivity,onNavigate}:{onActivity:(message:string)=>void;onNavigate:(tab:string)=>void}){
 const [data,setData]=useState<any>({shifts:[],tasks:[],context:null}),[busy,setBusy]=useState(false);
 const views=[{id:"overview",label:"Overview"},{id:"tasks",label:"Tasks"},{id:"shifts",label:"Shift calendar"},{id:"development",label:"Development"},{id:"career",label:"Career"},{id:"codebase",label:"Codebase & Business"}];
 const [view,setView]=useState<"overview"|"tasks"|"shifts"|"development"|"career"|"codebase">(()=>readSection("section",views.map(item=>item.id),"overview") as any);
 const [shiftMonth,setShiftMonth]=useState(new Date().toISOString().slice(0,7));
 const [task,setTask]=useState({title:"",area:"Sumitomo Rubber",priority:"Medium",dueDate:"",status:"Not started",notes:""});
 const [shift,setShift]=useState({date:today(),type:"day",start:"",end:"",notes:""});
 const load=async()=>{setBusy(true);try{const [overview,context,planTasks]=await Promise.all([fetch("/api/personal/overview").then(r=>r.json()),fetch("/api/ai/life-context").then(r=>r.json()),fetch("/api/tasks").then(r=>r.json())]);setData({shifts:overview.work?.shifts||[],tasks:overview.work?.tasks||[],planTasks:Array.isArray(planTasks)?planTasks:[],context,onboarding:overview.onboarding||{}})}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>updateSection("section",view),[view]);
 const run=async(url:string,method:string,body:any,message:string)=>{setBusy(true);try{const r=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const result=r.status===204?null:await r.json();if(!r.ok)throw new Error(result?.error||"Work update failed");onActivity(message);await load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 const open=data.tasks.filter((t:any)=>!["Completed","Done"].includes(t.status)),completed=data.tasks.filter((t:any)=>["Completed","Done"].includes(t.status)),overdue=open.filter((t:any)=>t.dueDate&&t.dueDate<today());
 const schedule=useMemo(()=>{const upcoming=[...data.shifts].filter((s:any)=>s.date>=today()).sort((a:any,b:any)=>a.date.localeCompare(b.date));return{today:upcoming.find((s:any)=>s.date===today())||null,nextWork:upcoming.find((s:any)=>["day","night"].includes(s.type))||null,upcoming:upcoming.slice(0,7)}},[data.shifts]);
 const hours=data.shifts.reduce((sum:number,s:any)=>{if(!s.start||!s.end||!["day","night"].includes(s.type))return sum;let start=new Date(`2000-01-01T${s.start}`),end=new Date(`2000-01-01T${s.end}`);if(end<start)end=new Date(end.getTime()+86400000);return sum+(end.getTime()-start.getTime())/3600000},0);
 return <div className="mx-auto max-w-7xl space-y-4"><PageHeader eyebrow="Team C · Sundays off" title="Work" description="Shifts, responsibilities, development and 43v3r business execution." actions={<button onClick={load} className="life-button-secondary flex items-center gap-2"><RefreshCw className={`h-3.5 w-3.5 ${busy?"animate-spin":""}`}/>Refresh</button>}/>
 <SegmentedTabs label="Work sections" items={views.map(item=>item.id==="tasks"?{...item,label:`Tasks (${open.length})`}:item)} value={view} onChange={id=>setView(id as any)}/>
 {view==="overview"&&<><div className="grid grid-cols-2 gap-2 md:grid-cols-5"><Metric label="Today's shift" value={schedule.today?.type||"Not set"}/><Metric label="Next work shift" value={schedule.nextWork?`${schedule.nextWork.date.slice(5)} · ${schedule.nextWork.type}`:"Not set"}/><Metric label="Open tasks" value={open.length}/><Metric label="Overdue" value={overdue.length} warn={!!overdue.length}/><Metric label="Completed" value={completed.length}/></div><div className="grid gap-4 lg:grid-cols-3"><Panel title="Priority work" icon={AlertTriangle}>{open.sort((a:any,b:any)=>String(a.dueDate||"9999").localeCompare(String(b.dueDate||"9999"))).slice(0,5).map((t:any)=><TaskRow key={t.id} task={t} onStatus={(status:string)=>run(`/api/personal/work/tasks/${t.id}`,"PATCH",{status},`Work task updated: ${t.title}`)}/>)}</Panel><Panel title="Upcoming rotation" icon={CalendarDays}>{schedule.upcoming.map((s:any)=><div key={s.id} className="border-b py-2 text-xs last:border-0"><strong>{s.date}</strong> · {s.type}{s.start?` · ${s.start}–${s.end}`:""}</div>)}{!schedule.upcoming.length&&<Empty text="No upcoming shifts saved."/>}</Panel><Panel title="Work intelligence" icon={Sparkles}><p className="text-xs leading-5 text-stone-600">LifeOS AI has access to {data.context?.work?.savedShifts||0} saved shifts and {data.context?.work?.savedTasks||0} saved work tasks. It now distinguishes today's assignment, your next working shift, and Sunday rest days.</p><div className="mt-3 rounded-lg bg-blue-50 p-3 text-xs"><strong>Development goal</strong><p className="mt-1 text-stone-600">{data.onboarding?.workDevelopmentGoal||"Not configured yet."}</p></div><button onClick={()=>onNavigate("chat")} className="mt-3 text-xs font-bold text-blue-700">Ask LifeOS AI about work</button></Panel></div></>}
 {view==="tasks"&&<div className="grid gap-4 lg:grid-cols-[360px_1fr]"><form onSubmit={e=>{e.preventDefault();if(!task.title)return;run("/api/personal/work/tasks","POST",task,`Work task saved: ${task.title}`);setTask({...task,title:"",dueDate:"",notes:""})}} className="h-fit space-y-3 rounded-2xl border p-4"><h3 className="font-semibold">Add work task</h3><input required className={input} placeholder="Task or outcome" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><input className={input} placeholder="Area or department" value={task.area} onChange={e=>setTask({...task,area:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className={input} value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select><input className={input} type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/></div><textarea className={input} placeholder="Notes" value={task.notes} onChange={e=>setTask({...task,notes:e.target.value})}/><button className="w-full rounded-lg bg-stone-900 p-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3 w-3"/>Save task</button></form><div className="space-y-2">{data.tasks.map((t:any)=><article key={t.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><strong className="text-sm">{t.title}</strong><p className="mt-1 text-xs text-stone-500">{t.area} · {t.priority} · {t.dueDate||"No deadline"}</p>{t.notes&&<p className="mt-2 text-xs text-stone-600">{t.notes}</p>}</div><button onClick={async()=>await confirmLifeOs(`Delete ${t.title}?`)&&run(`/api/personal/work/tasks/${t.id}`,"DELETE",null,`Work task deleted: ${t.title}`)}><Trash2 className="h-4 w-4 text-stone-400"/></button></div><select className={`${input} mt-3`} value={t.status} onChange={e=>run(`/api/personal/work/tasks/${t.id}`,"PATCH",{status:e.target.value},`Work task updated: ${t.title}`)}><option>Not started</option><option>In progress</option><option>Blocked</option><option>Completed</option></select></article>)}</div></div>}
 {view==="shifts"&&<div className="grid gap-4 lg:grid-cols-[360px_1fr]"><form onSubmit={e=>{e.preventDefault();run("/api/personal/work/shifts","POST",shift,`Work shift saved: ${shift.date}`)}} className="h-fit space-y-3 rounded-2xl border p-4"><h3 className="font-semibold">Add or override shift</h3><input required className={input} type="date" value={shift.date} onChange={e=>setShift({...shift,date:e.target.value})}/><select className={input} value={shift.type} onChange={e=>setShift({...shift,type:e.target.value})}><option value="day">Day shift</option><option value="night">Night shift</option><option value="off">Off</option><option value="leave">Leave</option></select><div className="grid grid-cols-2 gap-2"><input className={input} type="time" value={shift.start} onChange={e=>setShift({...shift,start:e.target.value})}/><input className={input} type="time" value={shift.end} onChange={e=>setShift({...shift,end:e.target.value})}/></div><textarea className={input} placeholder="Shift notes" value={shift.notes} onChange={e=>setShift({...shift,notes:e.target.value})}/><button className="w-full rounded-lg bg-stone-900 p-2 text-xs font-bold text-white">Save shift</button></form><div><div className="mb-3 flex items-center justify-between gap-2"><div><h3 className="text-sm font-semibold">Saved calendar</h3><p className="text-[10px] text-stone-500">{data.onboarding?.workShiftTeam?`Team ${data.onboarding.workShiftTeam} · ${data.onboarding.workShiftCalendarYear}`:"Manual shifts"}</p></div><input type="month" className={input} value={shiftMonth} onChange={e=>setShiftMonth(e.target.value)}/></div><div className="grid gap-2 sm:grid-cols-2">{[...data.shifts].filter((s:any)=>String(s.date).startsWith(shiftMonth)).sort((a:any,b:any)=>a.date.localeCompare(b.date)).map((s:any)=><article key={s.id} className={`rounded-xl border p-3 ${s.type==="day"?"border-amber-200 bg-amber-50":s.type==="night"?"border-blue-200 bg-blue-50":"bg-stone-50"}`}><div className="flex justify-between"><div><strong className="text-sm">{new Date(`${s.date}T12:00:00`).toLocaleDateString("en-ZA",{weekday:"short",day:"numeric",month:"short"})}</strong><p className="mt-1 text-xs capitalize text-stone-600">{s.type}{s.start?` · ${s.start}–${s.end}`:""}{s.team?` · Team ${s.team}`:""}</p>{s.notes&&<p className="mt-2 text-xs">{s.notes}</p>}</div><button onClick={async()=>await confirmLifeOs(`Delete shift on ${s.date}?`)&&run(`/api/personal/work/shifts/${s.id}`,"DELETE",null,`Work shift deleted: ${s.date}`)}><Trash2 className="h-4 w-4 text-stone-400"/></button></div></article>)}</div></div></div>}
 {view==="development"&&<Development current={data.onboarding?.workDevelopmentGoal||""} onSaved={load} onActivity={onActivity} onAsk={()=>onNavigate("chat")}/>}
 {view==="career"&&<CareerView onNavigate={onNavigate} onActivity={onActivity}/>}
 {view==="codebase"&&<CodebaseBusinessView existingTasks={data.planTasks||[]} onSaved={load} onActivity={onActivity} onAsk={()=>onNavigate("chat")}/>}</div>
}
function Development({current,onSaved,onActivity,onAsk}:any){const[value,setValue]=useState(current);useEffect(()=>setValue(current),[current]);return <div className="grid gap-4 lg:grid-cols-2"><form onSubmit={async e=>{e.preventDefault();const r=await fetch("/api/personal/onboarding",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({workDevelopmentGoal:value})});if(r.ok){onActivity("Work development goal saved.");onSaved()}}} className="space-y-3 rounded-2xl border p-5"><h3 className="font-semibold">Development goal</h3><p className="text-xs text-stone-500">Save the next skill, qualification or role outcome you are working toward.</p><textarea required className={input} value={value} onChange={e=>setValue(e.target.value)} placeholder="Example: qualify for the next technical role by…"/><button className="rounded-lg bg-stone-900 px-4 py-2 text-xs font-bold text-white">Save goal</button></form><div className="rounded-2xl border p-5"><h3 className="font-semibold">AI work coach</h3><p className="mt-2 text-xs leading-5 text-stone-500">Ask LifeOS to break this development goal into tasks, plan around shifts, prepare for reviews, or identify overdue work. Your saved work records are included only for work-related questions.</p><button onClick={onAsk} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white">Open assistant</button></div></div>}
function TaskRow({task,onStatus}:any){return <div className="flex items-center gap-2 border-b py-2 last:border-0"><button onClick={()=>onStatus("Completed")}><CheckCircle2 className="h-4 w-4 text-stone-300 hover:text-emerald-600"/></button><div className="min-w-0"><p className="truncate text-xs font-semibold">{task.title}</p><p className="text-[10px] text-stone-500">{task.priority} · {task.dueDate||"No deadline"}</p></div></div>}
function Panel({title,icon:Icon,children}:any){return <section className="rounded-2xl border p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><Icon className="h-4 w-4 text-blue-700"/>{title}</h3><div className="mt-3">{children}</div></section>}
function Metric({label,value,warn=false}:any){return <div className="rounded-xl border p-3"><span className="text-[9px] uppercase text-stone-500">{label}</span><strong className={`mt-1 block text-xl ${warn?"text-red-700":""}`}>{value}</strong></div>}
function Empty({text}:any){return <div className="py-6 text-center text-xs text-stone-500">{text}</div>}
